### ISSUE TITLE
pip install llama exits with NameError: name 'execfile' is not defined

### ISSUE THREAD

**Issue by enkiman** [facebookresearch/llama#1010]
**Before submitting a bug, please make sure the issue hasn't been already addressed by searching through the [FAQs](https://ai.meta.com/llama/faq/) and [existing/past issues](https://github.com/facebookresearch/llama/issues)**

## Describe the bug
Your example programs require the python package llama, however when I try and install the package pip displays the following error:

Collecting llama
  Using cached llama-0.1.1.tar.gz (387 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-zet92dop/llama_8f5b643b75d1469cb691dbfbb3d34adb/setup.py", line 6, in <module>
          execfile('llama/version.py')
          ^^^^^^^^
      NameError: name 'execfile' is not defined
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

All 0.x versions have the same error.  PyPi indicates this package is for python 2.x.  I am using 3.11.  I believe execfile was depricated on python 3.  Is there another package I should be using?

### Minimal reproducible example
pip install llama

```python
# sample code to repro the bug
```

### Output
<Remember to wrap the output in ```` ```triple-quotes blocks``` ````>

```
<paste stacktrace and other outputs here>
```

## Runtime Environment
- Model: [eg: `llama-2-7b-chat`] llama-2-7b-chat
- Using via huggingface?: [yes/no] no
- OS: [eg. Linux/Ubuntu, Windows] Linux
- GPU VRAM:  2G
- Number of GPUs: 1
- GPU Make: [eg: Nvidia, AMD, Intel] Nvidia

**Additional context**
Add any other context about the problem or environment here.

**Comment by enkiman** [comment]
You know it would help if I followed the directions!

The fix:
1) clone the repo  git clone https://github.com/facebookresearch/llama.git
2) pip install -e .

Done.
