### ISSUE TITLE
Fine-tuning LLaMA with TencentPretrain and DeepSpeed

### ISSUE THREAD

**Issue by ydli-ai** [facebookresearch/llama#169]
We implement LLaMA training on the [TencentPretrain framework](https://github.com/Tencent/TencentPretrain), the tutorial is as follows:

1. Clone the TencentPretrain project and install dependencies: PyTorch, DeepSpeed, SentencePiece

```
git clone https://github.com/Tencent/TencentPretrain.git
```

2. Convert LLaMA-7B weights to TencentPretrain format

```
cd TencentPretrain

python3 scripts/convert_llama_to_tencentpretrain.py --input_model_path $LLaMA_7B_FOLDER/consolidated.00.pth --output_model_path models/llama-7b.bin --layers_num 32
```

3. Modify configuration file

Check out the `tencentpretrain/utils/constants.py` file, and modify L4: `special_tokens_map.json` to `llama_special_tokens_map.json`

4. Data preprocess. We use the example corpus in the project for pre-training, one can also use custom data training in the same format (one sample per line).

```
python3 preprocess.py --corpus_path corpora/book_review.txt --spm_model_path $LLaMA_7B_FOLDER/tokenizer.model \
                      --dataset_path dataset.pt --processes_num 8 --data_processor lm
```

5. Start training. 

```
deepspeed pretrain.py --deepspeed --deepspeed_config models/deepspeed_config.json \
                      --pretrained_model_path models/llama-7b.bin \
                      --dataset_path dataset.pt --spm_model_path $LLaMA_7B_FOLDER/tokenizer.model \
                      --config_path models/llama/7b_config.json \
                      --output_model_path models/output_model.bin \
                      --world_size 8 --learning_rate 1e-4  \
                      --data_processor lm --total_steps 10000 --save_checkpoint_steps 2000 --batch_size 24
```

For now, TencentPretrain only support LLaMA-7B training. We are working on our framework to support LLaMA model training/fine-tuning at all scales and sharing more experimental results.

**Comment by lxe** [comment]
What's the hardware requirements for this?

**Comment by scampion** [comment]
On my side, I got the following error, with the current example: 
```
Traceback (most recent call last):
  File "/home/scampion/Code/TencentPretrain/pretrain.py", line 121, in <module>
    main()
  File "/home/scampion/Code/TencentPretrain/pretrain.py", line 117, in main
    trainer.train_and_validate(args)
  File "/home/scampion/Code/TencentPretrain/tencentpretrain/trainer.py", line 56, in train_and_validate
    worker(args.local_rank, None, args, model_for_training, model_for_dataloader)
  File "/home/scampion/Code/TencentPretrain/tencentpretrain/trainer.py", line 636, in worker
    trainer.train(args, gpu_id, rank, train_loader, model_for_training, optimizer, scheduler)
  File "/home/scampion/Code/TencentPretrain/tencentpretrain/trainer.py", line 101, in train
    batch = list(next(loader_iter))
  File "/home/scampion/Code/TencentPretrain/tencentpretrain/utils/dataloader.py", line 187, in __iter__
    yield torch.LongTensor(src), \
TypeError: 'NoneType' object cannot be interpreted as an integer
[2023-03-14 22:03:08,384] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2531564
[2023-03-14 22:03:09,896] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2531565
[2023-03-14 22:03:09,906] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2531566
[2023-03-14 22:03:09,906] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2531567
[2023-03-14 22:03:09,916] [ERROR] [launch.py:324:sigkill_handler] ['/home/scampion/Code/stanford_alpaca/venv/bin/python', '-u', 'pretrain.py', '--local_rank=3', '--deepspeed', '--deepspeed_config', 'models/deepspeed_config.json', '--pretrained_model_path', 'models/llama-7b.bin', '--dataset_path', 'dataset.pt', '--spm_model_path', '../../LLaMA/tokenizer.model', '--config_path', 'models/llama/7b_config.json', '--output_model_path', 'models/output_model.bin', '--world_size', '8', '--learning_rate', '1e-4', '--data_processor', 'lm', '--total_steps', '10000', '--save_checkpoint_steps', '2000', '--batch_size', '24'] exits with return code = 1
```

**Comment by Ageliss** [comment]
Any improved chat results?

**Comment by lxe** [comment]
I'm guessing `--world_size 8` means it's a cluster of 8 GPUs

**Comment by ydli-ai** [comment]
> I'm guessing `--world_size 8` means it's a cluster of 8 GPUs

We only tested it on 8 * A100, --world_size 8 means GPU nums.

**Comment by scampion** [comment]
torch.cuda.OutOfMemoryError: CUDA out of memory.
I'll try to change some parameter (current config 4x A5000 with 24GB/GPU)

**Comment by haoemo** [comment]
cool, follow you steps.

**Comment by xihajun** [comment]
@Coderx7 https://github.com/tatsu-lab/stanford_alpaca maybe can check this

**Comment by Charuru** [comment]
@ydli-ai any updates on this? Does this work at all on something like a 4090?

**Comment by sourcesync** [comment]
If I'm not mistaken, the code at the top is a train-from-scratch example ( Tencent seems to call it pre-training ) but not fine-tuning.  If so, is there a fine-tuning example for instruction-following @ydli-ai ?

**Comment by ze00ro** [comment]
pretrain hardware requirements?
