### ISSUE TITLE
AssertionError: Loading a checkpoint for MP=0 but world size is 2

### ISSUE THREAD

**Issue by jamestch** [facebookresearch/llama#182]
Hello all,

I'm trying to use the 13B model on a machine with two GPUs (NVIDIA Tesla V100s, 32GB) with the following command:
$torchrun --nproc_per_node 2 example.py --ckpt_dir /path_to/llama/13B --tokenizer_path /path_to/llama/tokenizer.model
I get the error:

Traceback (most recent call last):
  File "example.py", line 120, in <module>
Traceback (most recent call last):
  File "example.py", line 120, in <module>
    fire.Fire(main)
  File "/opt/data/private/anaconda3/envs/llama/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    fire.Fire(main)
  File "/opt/data/private/anaconda3/envs/llama/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/data/private/anaconda3/envs/llama/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/data/private/anaconda3/envs/llama/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/data/private/anaconda3/envs/llama/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "example.py", line 79, in main
    generator = load(
  File "example.py", line 43, in load
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/data/private/anaconda3/envs/llama/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    assert world_size == len(
_**AssertionError: Loading a checkpoint for MP=0 but world size is 2**_
    component = fn(*varargs, **kwargs)
  File "example.py", line 79, in main
    generator = load(
  File "example.py", line 43, in load
    assert world_size == len(
_**AssertionError: Loading a checkpoint for MP=0 but world size is 2**_
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 205991) of binary: /opt/data/private/anaconda3/envs/llama/bin/python
Traceback (most recent call last):
  File "/opt/data/private/anaconda3/envs/llama/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.11.0', 'console_scripts', 'torchrun')())
  File "/opt/data/private/anaconda3/envs/llama/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/opt/data/private/anaconda3/envs/llama/lib/python3.8/site-packages/torch/distributed/run.py", line 724, in main
    run(args)
  File "/opt/data/private/anaconda3/envs/llama/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/opt/data/private/anaconda3/envs/llama/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/data/private/anaconda3/envs/llama/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

Thanks for any help!

**Comment by sallywang147** [comment]
following - I have the same error

**Comment by catid** [comment]
This happens if the model directory path is incorrect

**Comment by jamestch** [comment]
> This happens if the model directory path is incorrect

yes, I have checked the model file path and it works! Thanks for your help

**Comment by leo2714** [comment]
I have the same error,what is your model file path?

**Comment by starplatinum3** [comment]
May I ask if 13b will require two graphics cards

**Comment by roots-ai** [comment]
`python3 -m torch.distributed.launch --nproc_per_node=1 example_chat_completion.py --ckpt_dir llama-2-13b-chat/ --tokenizer_path tokenizer.model --max_seq_len 512 --max_batch_size 4`
is this wrong?
