### ISSUE TITLE
Unable to run 13B model on CPU

### ISSUE THREAD

**Issue by stduhpf** [facebookresearch/llama#224]
By removing references to cuda and changing the torch backend from "nccl" to "gloo" just like in the fork by [markasoftware](https://github.com/markasoftware/llama-cpu), I got the 7B model to work fine on my CPU. But when trying to run the 13B model using  `torchrun --nproc_per_node 2 example.py --ckpt_dir ./13B --tokenizer_path ./tokenizer.model`, the model still loads (and fills most of my memory in the process), but the generation crashes at the first call to `self.model.forward()` , with `RuntimeError: Invalid scalar type` 

here is the stack trace  of the exception
```
Traceback (most recent call last):
  File "C:\Users\me\llama\llama-cpu\example.py", line 142, in <module>
    fire.Fire(main)
  File "C:\Users\me\.conda\envs\llamacpu\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\me\.conda\envs\llamacpu\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\me\.conda\envs\llamacpu\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\me\llama\llama-cpu\example.py", line 129, in main
    results = generator.generate(
  File "C:\Users\me\llama\llama-cpu\llama\generation.py", line 50, in generate
    logits = self.model.forward(tokens[:, prev_pos:cur_pos], prev_pos)
  File "C:\Users\me\.conda\envs\llamacpu\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\me\llama\llama-cpu\llama\model.py", line 225, in forward
    h = self.tok_embeddings(tokens)
  File "C:\Users\me\.conda\envs\llamacpu\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\me\.conda\envs\llamacpu\lib\site-packages\fairscale\nn\model_parallel\layers.py", line 214, in forward
    output = gather_from_model_parallel_region(output_parallel)
  File "C:\Users\me\.conda\envs\llamacpu\lib\site-packages\fairscale\nn\model_parallel\mappings.py", line 156, in gather_from_model_parallel_region
    return _GatherFromModelParallelRegion.apply(input_)
  File "C:\Users\me\.conda\envs\llamacpu\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\me\.conda\envs\llamacpu\lib\site-packages\fairscale\nn\model_parallel\mappings.py", line 131, in forward
    return _gather(input_)
  File "C:\Users\me\.conda\envs\llamacpu\lib\site-packages\fairscale\nn\model_parallel\mappings.py", line 82, in _gather
    torch.distributed.all_gather(tensor_list, input_, group=group)
  File "C:\Users\me\.conda\envs\llamacpu\lib\site-packages\torch\distributed\distributed_c10d.py", line 1436, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\me\.conda\envs\llamacpu\lib\site-packages\torch\distributed\distributed_c10d.py", line 2440, in all_gather
    work.wait()
RuntimeError: Invalid scalar type
```
It confuses me because the exact same argument is given to `self.model.forward()`  in the case of the 7B model, and it doesn't crash.  I guess it has something to do with the two process having communication issues.

**Comment by dongwang218** [comment]
llama-2-13b works on CPU with 2 processes with a patch https://github.com/facebookresearch/llama/issues/333#issuecomment-1710681365. Please reopen if there are still issues.
