### ISSUE TITLE
multi GPU error

### ISSUE THREAD

**Issue by yuxuan2015** [facebookresearch/llama#228]
torchrun --nproc_per_node gpu example.py --ckpt_dir pyllama_data/7B --tokenizer_path pyllama_data/tokenizer.model

Traceback (most recent call last):
  File "/data1/Semantic_team/speech/chatgpt/llama/example.py", line 119, in <module>
Traceback (most recent call last):
  File "/data1/Semantic_team/speech/chatgpt/llama/example.py", line 119, in <module>
    fire.Fire(main)
  File "/data1/anaconda3/envs/llama_py310/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    fire.Fire(main)
  File "/data1/anaconda3/envs/llama_py310/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/data1/anaconda3/envs/llama_py310/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/data1/anaconda3/envs/llama_py310/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
Traceback (most recent call last):
  File "/data1/Semantic_team/speech/chatgpt/llama/example.py", line 119, in <module>
        component, remaining_args = _CallAndUpdateTrace(component, remaining_args = _CallAndUpdateTrace(

  File "/data1/anaconda3/envs/llama_py310/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
  File "/data1/anaconda3/envs/llama_py310/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    fire.Fire(main)
  File "/data1/anaconda3/envs/llama_py310/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component = fn(*varargs, **kwargs)    
component_trace = _Fire(component, args, parsed_flag_args, context, name)  File "/data1/Semantic_team/speech/chatgpt/llama/example.py", line 78, in main

  File "/data1/anaconda3/envs/llama_py310/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component = fn(*varargs, **kwargs)
  File "/data1/Semantic_team/speech/chatgpt/llama/example.py", line 78, in main
    generator = load(
  File "/data1/Semantic_team/speech/chatgpt/llama/example.py", line 42, in load
    generator = load(
  File "/data1/Semantic_team/speech/chatgpt/llama/example.py", line 42, in load
    assert world_size == len(
AssertionError: Loading a checkpoint for MP=1 but world size is 4
        assert world_size == len(component, remaining_args = _CallAndUpdateTrace(

  File "/data1/anaconda3/envs/llama_py310/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
AssertionError: Loading a checkpoint for MP=1 but world size is 4
    component = fn(*varargs, **kwargs)
  File "/data1/Semantic_team/speech/chatgpt/llama/example.py", line 78, in main
    generator = load(
  File "/data1/Semantic_team/speech/chatgpt/llama/example.py", line 42, in load
    assert world_size == len(
AssertionError: Loading a checkpoint for MP=1 but world size is 4
Traceback (most recent call last):
  File "/data1/Semantic_team/speech/chatgpt/llama/example.py", line 119, in <module>
    fire.Fire(main)
  File "/data1/anaconda3/envs/llama_py310/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/data1/anaconda3/envs/llama_py310/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/data1/anaconda3/envs/llama_py310/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/data1/Semantic_team/speech/chatgpt/llama/example.py", line 78, in main
    generator = load(
  File "/data1/Semantic_team/speech/chatgpt/llama/example.py", line 42, in load
    assert world_size == len(
AssertionError: Loading a checkpoint for MP=1 but world size is 4
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 8748) of binary: /data1/anaconda3/envs/llama_py310/bin/python3.1
Traceback (most recent call last):
  File "/data1/anaconda3/envs/llama_py310/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/data1/anaconda3/envs/llama_py310/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/data1/anaconda3/envs/llama_py310/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/data1/anaconda3/envs/llama_py310/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/data1/anaconda3/envs/llama_py310/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data1/anaconda3/envs/llama_py310/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-03-22_17:02:34
  host      : bb6
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 8749)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-03-22_17:02:34
  host      : bb6
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 8750)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-03-22_17:02:34
  host      : bb6
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 8751)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-22_17:02:34
  host      : bb6
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 8748)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by papasega** [comment]
Hello, I have the same error  :

""" AssertionError: Loading a checkpoint for MP=1 but world size is 4
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 8748) of binary: /data1/anaconda3/envs/llama_py310/bin/python3."""

And I fixe it by : 

`torchrun --nproc_per_node 1 example.py --ckpt_dir $TARGET_FOLDER/7B ......`

I think you have to fixe --nproc_per_node buy the number of GPU you have. In my case I have just 1

**Comment by ejsd1989** [comment]
@yuxuan2015 @kechan checking in to see if this was resolved in your testing?
