### ISSUE TITLE
Unable to download from link XML/ Access Denied

### ISSUE THREAD

**Issue by TheCubanMan** [facebookresearch/llama#312]
Neither by curl -O nor by simply clicking the link I always get "XML Access Denied" I have tried different IP's and browsers and still get blocked. I used the newest download.sh file for mac in the earlier discussions from March and still nothing. I got the email less than 48 hrs ago so it shouldn't be expired. I'm very very beginner, I'm still learning everything there is to know about python, so please keep that in mind. I did my best with ChatGPT but to no avail. I run an M1 Mac and I know it's not ideal but not all of us have A100's ;). Please help and yes I have downloaded just about every conda, brew, pip, and whatever other ones I saw mentioned here but if you feel there is another one that will fix this, let me know. Thank you! When I try to run the torchrun --nproc_per_node 1 example.py --ckpt_dir /path/to/model/model_size --tokenizer_path /path/to/model/tokenizer.model I am also unable to get anything usefull done, this is the error I receive:
````
NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "/Users/theredbaron/mambaforge/envs/myenv/llama/example.py", line 119, in <module>
    fire.Fire(main)
  File "/Users/theredbaron/mambaforge/envs/myenv/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/theredbaron/mambaforge/envs/myenv/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/theredbaron/mambaforge/envs/myenv/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/theredbaron/mambaforge/envs/myenv/llama/example.py", line 74, in main
    local_rank, world_size = setup_model_parallel()
  File "/Users/theredbaron/mambaforge/envs/myenv/llama/example.py", line 23, in setup_model_parallel
    torch.distributed.init_process_group("nccl")
  File "/Users/theredbaron/mambaforge/envs/myenv/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 907, in init_process_group
  default_pg = _new_process_group_helper(
  File "/Users/theredbaron/mambaforge/envs/myenv/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1013, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 8272) of binary: /Users/theredbaron/mambaforge/envs/myenv/bin/python3.10
Traceback (most recent call last):
  File "/Users/theredbaron/mambaforge/envs/myenv/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/Users/theredbaron/mambaforge/envs/myenv/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
File "/Users/theredbaron/mambaforge/envs/myenv/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/Users/theredbaron/mambaforge/envs/myenv/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/Users/theredbaron/mambaforge/envs/myenv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/Users/theredbaron/mambaforge/envs/myenv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```
============================================================
example.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-25_23:59:42
  host      : 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 8272)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================``

**Comment by agunapal** [comment]
Hi @TheCubanMan Please refer to this Download FAQ
https://github.com/facebookresearch/llama/blob/bug-fix-Sep6/Download.md

Please reopen the issue if the issue persists
