### ISSUE TITLE
There is bug in trainer:indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by 2018211801** [facebookresearch/llama#326]
**I'm sure there is no problem with my code because others work fine. I'm guessing it's an issue with incompatible environment configurations.**

Parameter Offload: Total persistent parameters: 266240 in 65 params
  0%|                                                                                                    | 0/87850 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/mnt/data/wxc/workspace/release/start_ds_finetune.py", line 118, in <module>
    train()
  File "/mnt/data/wxc/workspace/release/start_ds_finetune.py", line 112, in train
    trainer.train()
  File "/mnt/data/wxc/workspace/Llama-X/src/transformers/src/transformers/trainer.py", line 1661, in train
    return inner_training_loop(
  File "/mnt/data/wxc/workspace/Llama-X/src/transformers/src/transformers/trainer.py", line 1946, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/mnt/data/wxc/workspace/Llama-X/src/transformers/src/transformers/trainer.py", line 2756, in training_step
    loss = self.compute_loss(model, inputs)
  File "/mnt/data/wxc/workspace/Llama-X/src/transformers/src/transformers/trainer.py", line 2781, in compute_loss
    outputs = model(**inputs)
  File "/home/wxc/miniconda3/envs/llamax/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wxc/miniconda3/envs/llamax/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/wxc/miniconda3/envs/llamax/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1733, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/wxc/miniconda3/envs/llamax/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/mnt/data/wxc/workspace/Llama-X/src/transformers/src/transformers/models/llama/modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "/home/wxc/miniconda3/envs/llamax/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/mnt/data/wxc/workspace/Llama-X/src/transformers/src/transformers/models/llama/modeling_llama.py", line 570, in forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "/home/wxc/miniconda3/envs/llamax/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/wxc/miniconda3/envs/llamax/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/mnt/data/wxc/workspace/Llama-X/src/transformers/src/transformers/models/llama/modeling_llama.py", line 566, in custom_forward
    return module(*inputs, output_attentions, None)
  File "/home/wxc/miniconda3/envs/llamax/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/mnt/data/wxc/workspace/Llama-X/src/transformers/src/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/wxc/miniconda3/envs/llamax/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/mnt/data/wxc/workspace/Llama-X/src/transformers/src/transformers/models/llama/modeling_llama.py", line 202, in forward
    query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin, position_ids)
  File "/mnt/data/wxc/workspace/Llama-X/src/transformers/src/transformers/models/llama/modeling_llama.py", line 134, in apply_rotary_pos_emb
    cos = cos[position_ids].unsqueeze(1)  # [bs, 1, seq_len, dim]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

**Here is part of my conda list:**

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
_openmp_mutex             4.5                       2_gnu    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
absl-py                   1.4.0                    pypi_0    pypi
accelerate                0.19.0                   pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
anyio                     3.7.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
bcrypt                    4.0.1                    pypi_0    pypi
blas                      1.0                         mkl    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
brotli                    1.0.9                h166bdaf_8    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
brotli-bin                1.0.9                h166bdaf_8    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
bzip2                     1.0.8                h7f98852_4    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2023.5.7             hbcca054_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        3.1.0              pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
click                     8.1.3                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cryptography              41.0.1                   pypi_0    pypi
cudatoolkit               11.3.1              h9edb442_11    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
cycler                    0.11.0                   pypi_0    pypi
datasets                  2.12.0                   pypi_0    pypi
deepspeed                 0.9.3+e02b8d0b           pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
exceptiongroup            1.1.1                    pypi_0    pypi
fastapi                   0.96.0                   pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
ffmpy                     0.3.0                    pypi_0    pypi
filelock                  3.12.0                   pypi_0    pypi
fire                      0.5.0                    pypi_0    pypi
fonttools                 4.39.4                   pypi_0    pypi
freetype                  2.12.1               hca18f0e_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.5.0                 pypi_0    pypi
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.31                   pypi_0    pypi
gmp                       6.2.1                h58526e2_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
gnutls                    3.6.13               h85f3911_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
gradio                    3.9                      pypi_0    pypi
h11                       0.12.0                   pypi_0    pypi
hjson                     3.1.0                    pypi_0    pypi
httpcore                  0.15.0                   pypi_0    pypi
httpx                     0.24.1                   pypi_0    pypi
huggingface-hub           0.15.1                   pypi_0    pypi
idna                      3.4                pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
intel-openmp              2021.4.0          h06a4308_3561    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9e                   h0b41bf4_3    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
lame                      3.100             h166bdaf_1003    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
lcms2                     2.12                 hddcbb42_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
lerc                      3.0                  h9c3ff4c_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libbrotlicommon           1.0.9                h166bdaf_8    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libbrotlidec              1.0.9                h166bdaf_8    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libbrotlienc              1.0.9                h166bdaf_8    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libdeflate                1.10                 h7f98852_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libffi                    3.4.2                h7f98852_5    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libgcc-ng                 12.2.0              h65d4601_19    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libgomp                   12.2.0              h65d4601_19    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libiconv                  1.14                          0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libnsl                    2.0.0                h7f98852_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libpng                    1.6.39               h753d276_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libsqlite                 3.42.0               h2797004_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libtiff                   4.3.0                h0fcbabc_4    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libuuid                   2.38.1               h0b41bf4_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libwebp-base              1.3.0                h0b41bf4_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libzlib                   1.2.13               h166bdaf_4    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
linkify-it-py             2.0.2                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
mdit-py-plugins           0.3.5                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
mkl-fft                   1.3.1                    pypi_0    pypi
mkl-random                1.2.2                    pypi_0    pypi
mkl-service               2.4.0                    pypi_0    pypi
mkl_fft                   1.3.1           py310h2b4bcf5_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
mkl_random                1.2.2           py310h00e6091_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
multidict                 6.0.4                    pypi_0    pypi
multiprocess              0.70.14                  pypi_0    pypi
ncurses                   6.3                  h27087fc_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
nettle                    3.6                  he412f7d_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
ninja                     1.11.1                   pypi_0    pypi
nltk                      3.8.1                    pypi_0    pypi
numpy                     1.24.3                   pypi_0    pypi
numpy-base                1.24.3          py310h8e6c178_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
olefile                   0.46               pyh9f0ad1d_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
openai                    0.27.7                   pypi_0    pypi
openh264                  2.1.1                h780b84a_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
openjpeg                  2.5.0                h7d73246_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
openssl                   3.1.1                hd590300_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
orjson                    3.9.0                    pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.2                    pypi_0    pypi
paramiko                  3.2.0                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pillow                    8.4.0                    pypi_0    pypi
pip                       23.1.2             pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
protobuf                  3.20.3                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyarrow                   12.0.0                   pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pycryptodome              3.18.0                   pypi_0    pypi
pydantic                  1.10.8                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pynacl                    1.5.0                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1                    pypi_0    pypi
python                    3.10.11         he550d4f_0_cpython    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-dotenv             1.0.0                    pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
python_abi                3.10                    3_cp310    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
pytorch                   1.12.0          py3.10_cuda11.3_cudnn8.3.2_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
pytorch-mutex             1.0                        cuda    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h8228510_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
regex                     2023.6.3                 pypi_0    pypi
requests                  2.31.0             pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
responses                 0.18.0                   pypi_0    pypi
rouge-score               0.1.2                    pypi_0    pypi
safetensors               0.3.1                    pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
sentry-sdk                1.25.0                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                67.7.2             pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
six                       1.16.0             pyh6c4a22f_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
starlette                 0.27.0                   pypi_0    pypi
tensorboardx              2.6                      pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
tokenizers                0.13.3                   pypi_0    pypi
torch                     1.13.1+cu116             pypi_0    pypi
torchaudio                0.13.1+cu116             pypi_0    pypi
torchvision               0.14.1+cu116             pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
transformers              4.30.0.dev0              pypi_0    pypi

**Comment by 2018211801** [comment]
**And other configuration for llama:**
{
  "_name_or_path": "huggyllama/llama-7b",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 2048,
  "max_sequence_length": 2048,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "pad_token_id": 0,
  "rms_norm_eps": 1e-06,
  "tie_word_embeddings": false,
  "torch_dtype": "float32",
  "transformers_version": "4.30.0.dev0",
  "use_cache": true,
  "vocab_size": 32000
}


{
  "bos_token": {
    "__type": "AddedToken",
    "content": "<s>",
    "lstrip": false,
    "normalized": true,
    "rstrip": false,
    "single_word": false
  },
  "clean_up_tokenization_spaces": false,
  "eos_token": {
    "__type": "AddedToken",
    "content": "</s>",
    "lstrip": false,
    "normalized": true,
    "rstrip": false,
    "single_word": false
  },
  "model_max_length": 2048,
  "pad_token": null,
  "sp_model_kwargs": {},
  "tokenizer_class": "LlamaTokenizer",
  "unk_token": {
    "__type": "AddedToken",
    "content": "<unk>",
    "lstrip": false,
    "normalized": true,
    "rstrip": false,
    "single_word": false
  }
}

**Comment by LianghuiGuo** [comment]
兄弟解决了吗，我训练LLAVA也遇到这个问题
