### ISSUE TITLE
Running example on WSL RTX 3090

### ISSUE THREAD

**Issue by AnishPahilajani** [facebookresearch/llama#334]
I am trying to run the following command:

` torchrun --nproc_per_node 1 example.py --ckpt_dir downloads/7B --tokenizer_path downloads/tokenizer.model`

I am getting the following error: The similar error gets repeated for every layer

```
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Loading
Traceback (most recent call last):
  File "/home/anish/Anish/llama/llama/example.py", line 119, in <module>
    fire.Fire(main)
  File "/home/anish/mambaforge/envs/llama/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/anish/mambaforge/envs/llama/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/anish/mambaforge/envs/llama/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/anish/Anish/llama/llama/example.py", line 78, in main
    generator = load(
  File "/home/anish/Anish/llama/llama/example.py", line 59, in load
    model.load_state_dict(checkpoint, strict=False)
  File "/home/anish/mambaforge/envs/llama/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Transformer:
        While copying the parameter named "layers.4.feed_forward.w3.weight", whose dimensions in the model are torch.Size([11008, 4096]) and whose dimensions in the checkpoint are torch.Size([11008, 4096]), an exception occurred : ('CUDA error: unknown error\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
        While copying the parameter named "layers.4.attention_norm.weight", whose dimensions in the model are torch.Size([4096]) and whose dimensions in the checkpoint are torch.Size([4096]), an exception occurred : ('CUDA error: unknown error\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
       .
.
.
.
.
.

        While copying the parameter named "output.weight", whose dimensions in the model are torch.Size([32000, 4096]) and whose dimensions in the checkpoint are torch.Size([32000, 4096]), an exception occurred : ('CUDA error: unknown error\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1412) of binary: /home/anish/mambaforge/envs/llama/bin/python3.10
Traceback (most recent call last):
  File "/home/anish/mambaforge/envs/llama/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/anish/mambaforge/envs/llama/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/anish/mambaforge/envs/llama/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/anish/mambaforge/envs/llama/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/anish/mambaforge/envs/llama/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/anish/mambaforge/envs/llama/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
example.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-21_22:49:56
  host      : A3090.
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1412)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by AnishPahilajani** [comment]
I just restarted my terminal and it works!! I have no idea what was wrong
