### ISSUE TITLE
Runing 7B: CUDA out of memory with 256gb ram?

### ISSUE THREAD

**Issue by Karlo-Emilo** [facebookresearch/llama#335]
I am running out of memory when i try to run the 7B model and i cannot figure out why. I am using a a computing instance on Azure ML studio with 24 cores, 224 GB RAM, 1440 GB disk and 4 x NVIDIA Tesla K80.

This is the error message:

```shell
torchrun --nproc_per_node 1 example.py --ckpt_dir weights/7B --tokenizer_path weights/tokenizer.model
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Loading
Traceback (most recent call last):
  File "example.py", line 119, in <module>
    fire.Fire(main)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "example.py", line 78, in main
    generator = load(
  File "example.py", line 57, in load
    model = Transformer(model_args)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/au5242523/code/Users/au524252/llama/llama/model.py", line 211, in __init__
    self.layers.append(TransformerBlock(layer_id, params))
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/au5242523/code/Users/au524252/llama/llama/model.py", line 184, in __init__
    self.attention = Attention(args)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/au5242523/code/Users/au524252/llama/llama/model.py", line 90, in __init__
    self.wk = ColumnParallelLinear(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/fairscale/nn/model_parallel/layers.py", line 262, in __init__
    self.weight = Parameter(torch.Tensor(self.output_size_per_partition, self.in_features))
RuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 11.17 GiB total capacity; 10.82 GiB already allocated; 6.25 MiB free; 10.82 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 6825) of binary: /anaconda/envs/azureml_py38/bin/python
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-22_12:39:31
  host      : localhost
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 6825)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

``` 

And these outputs are are from just before the error Occurred:

```shell
nvidia-smi
Thu Jun 22 12:39:24 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000001:00:00.0 Off |                    0 |
| N/A   40C    P0    55W / 149W |    703MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 00000002:00:00.0 Off |                    0 |
| N/A   32C    P8    32W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 00000003:00:00.0 Off |                    0 |
| N/A   36C    P8    26W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 00000004:00:00.0 Off |                    0 |
| N/A   30C    P8    31W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      6825      C   ...s/azureml_py38/bin/python      700MiB |
+-----------------------------------------------------------------------------+
``` 

```shell
free -h
              total        used        free      shared  buff/cache   available
Mem:          220Gi        15Gi       190Gi        23Mi        14Gi       203Gi
Swap:          61Gi          0B        61Gi
``` 

There is probably something here that I am missing or have misunderstood. I Hope you can help me.

Thanks!

**Comment by ganeshkrishnan1** [comment]
it looks like your GPU is 12 GB. You can see torch failing trying to allocate ram to 12 GB device.

"free -h" shows system memory not gpu ram.

**Comment by Lastdier** [comment]
As far as I know, you are using the DDP script which sets the usage of the GPU based on the word_id. You can see because you select 1 process per node, the second line shows "model parallel with size 1". In the script, the model will be loaded on GPU 0 (only this GPU is used). So, the model won't be loaded on all four of your GPUs. And your single GPU can fit the model, which leads to the error.

**Comment by penguinyou88** [comment]
> As far as I know, you are using the DDP script which sets the usage of the GPU based on the word_id. You can see because you select 1 process per node, the second line shows "model parallel with size 1". In the script, the model will be loaded on GPU 0 (only this GPU is used). So, the model won't be loaded on all four of your GPUs. And your single GPU can fit the model, which leads to the error.

Having the same problem here. So how to modify the code so the model is loaded with all 4 GPUs?

**Comment by Karlo-Emilo** [comment]
> As far as I know, you are using the DDP script which sets the usage of the GPU based on the word_id. You can see because you select 1 process per node, the second line shows "model parallel with size 1". In the script, the model will be loaded on GPU 0 (only this GPU is used). So, the model won't be loaded on all four of your GPUs. And your single GPU can fit the model, which leads to the error.

That is indeed the issue. Thanks for the input @Lastdier 

> Having the same problem here. So how to modify the code so the model is loaded with all 4 GPUs?

@penguinyou88, I have not tested it yet with the example.y script, but my guess would be to change the --nproc_per_node parameter the number of GPUs you want to use.
