### ISSUE TITLE
Runtime Error while creating spaces in Huggingface using chat-hf (Could not find model)

### ISSUE THREAD

**Issue by d-dutta** [facebookresearch/llama#399]
Hi, I am getting below when I am trying to load model in Huggingface spaces. Tried with 70B and 13B hf chat models and get the same with both:

Runtime error
/home/user/app/app.py:3: GradioDeprecationWarning: gr.Interface.load() will be deprecated. Use gr.load() instead.
  gr.Interface.load("models/meta-llama/Llama-2-7b-chat-hf").launch()
Fetching model from: https://huggingface.co/meta-llama/Llama-2-7b-chat-hf
Traceback (most recent call last):
  File "/home/user/app/app.py", line 3, in <module>
    gr.Interface.load("models/meta-llama/Llama-2-7b-chat-hf").launch()
  File "/home/user/.local/lib/python3.10/site-packages/gradio/interface.py", line 98, in load
    return external.load(
  File "/home/user/.local/lib/python3.10/site-packages/gradio/external.py", line 70, in load
    return load_blocks_from_repo(
  File "/home/user/.local/lib/python3.10/site-packages/gradio/external.py", line 109, in load_blocks_from_repo
    blocks: gradio.Blocks = factory_methods[src](name, hf_*****, alias, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/gradio/external.py", line 149, in from_model
    response.status_code == 200
AssertionError: Could not find model: meta-llama/Llama-2-7b-chat-hf. If it is a private or gated model, please provide your Hugging Face access token (https://huggingface.co/settings/tokens) as the argument for the `api_key` parameter.

![image](https://github.com/facebookresearch/llama/assets/10782654/90c5d251-9ac8-44d7-8b31-ece625dea3df)
![image](https://github.com/facebookresearch/llama/assets/10782654/e3914c94-2f4d-403c-ba00-b1faf36bb56b)
![image](https://github.com/facebookresearch/llama/assets/10782654/b14885fd-7224-4487-bc66-79a0d441e7f2)
![image](https://github.com/facebookresearch/llama/assets/10782654/18299ac4-3a94-4a10-a5e6-9d39284dc7a1)
![image](https://github.com/facebookresearch/llama/assets/10782654/8cef68bb-403f-42fc-964f-b63b67434933)

**Comment by pelinbalci** [comment]
I'm facing the same problem. Did you find a solution @d-dutta?

**Comment by bmz1** [comment]
Same

**Comment by bmz1** [comment]
ok, I've got it working, just add a `HF_TOKEN` to your secrets in the repo

**Comment by xiuwei1026** [comment]
> ok, I've got it working, just add a `HF_TOKEN` to your secrets in the repo

Have the same issue. Could you please elaborate how to add the token? Tried to add in setting/secret but it didn't work

**Comment by devhindo** [comment]
> ok, I've got it working, just add a `HF_TOKEN` to your secrets in the repo

where to get that?

**Comment by ujjwalkarn** [comment]
cc: @osanseviero in case you can help here.

**Comment by osanseviero** [comment]
Hi there! You can create tokens at https://huggingface.co/settings/tokens

**Comment by soymartinez** [comment]
1. creates a token of type `READ`: https://huggingface.co/settings/tokens

2. create a new `secret` in your space configuration.
It may need a specific name, for example `HF_TOKEN`. 
The value is the generated token, paste it here.
<img width="981" alt="image" src="https://github.com/meta-llama/llama/assets/72507996/2be4ea56-fd54-4d5b-9c94-ced82c10cdbc">

3. open `app.py` from space files:
<img width="470" alt="image" src="https://github.com/meta-llama/llama/assets/72507996/eac81a1e-581a-45fe-91f8-b2aa8d2ce568">
open:
<img width="957" alt="image" src="https://github.com/meta-llama/llama/assets/72507996/b31c9680-215c-4c70-b65e-5de30caaf38c">

4. add the created `secret` as a parameter of `.load`:
```python
import gradio as gr
import os

# IMPORT HF_TOKEN
hf_token = os.environ['HF_TOKEN']

# PROVIDE YOUR ACCESS TOKEN AS AN ARGUMENT TO THE hf_token PARAMETER
gr.load("models/soymartinez/model-name", hf_token=hf_token).launch()
```

5. commit and restart space (automatic restart on commit)




> [!NOTE]
> the name of the parameter depends on your error, in your case it would be `api_key`.
> ```python
> gr.load("models/account-name/model-name", api_key=api_key).launch()
> ```
