### ISSUE TITLE
Am not able to run 13b-chat on my Mac M1 Pro

### ISSUE THREAD

**Issue by araby123** [facebookresearch/llama#405]
when. I try this code 
`torchrun --nproc_per_node 1 example_chat_completion.py \
    --ckpt_dir llama-2-13b-chat/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 512 --max_batch_size 4`

it show this error : 
`RuntimeError: Distributed package doesn't have NCCL built in`

any idea how to solve this ?

**Comment by krychu** [comment]
Try a forked version that is adapted to run on the CPU: https://github.com/krychu/llama

**Comment by khirasaki** [comment]
Thanks for the fork! I fired up the 7B, and it loaded up, but then it pegged my M2 Max's CPUs for minutes without anything happening based on the example script. It was getting so hot in my lap that I killed the process to get back to work. 😆

**Comment by aggiee** [comment]
Another forked version adapted for M1/M2 MPS - example_text_completion.py  seems to work reasonably well with 7B Llama2 model on M2 - https://github.com/aggiee/llama-v2-mps

**Comment by krychu** [comment]
> Thanks for the fork! I fired up the 7B, and it loaded up, but then it pegged my M2 Max's CPUs for minutes without anything happening based on the example script. It was getting so hot in my lap that I killed the process to get back to work. 😆

No worries, but apologies for pegging your machine! :) I've made a few updates. It'll now use Mac GPU if available but also report speed at which tokens are being generated.

**Comment by araby123** [comment]
> Another forked version adapted for M1/M2 MPS - example_text_completion.py seems to work reasonably well with 7B Llama2 model on M2 - https://github.com/aggiee/llama-v2-mps

I try this same issue is appearing

**Comment by araby123** [comment]
> Try a forked version that is adapted to run on the CPU: https://github.com/krychu/llama

this worked but in too much slow performance 
<img width="1640" alt="Screenshot 2023-07-23 at 2 31 32 PM" src="https://github.com/facebookresearch/llama/assets/7244313/74fc7862-6d66-4f45-80cb-c9cbc8c12f5c">

**Comment by Tiru-Kaggundi** [comment]
> Try a forked version that is adapted to run on the CPU: https://github.com/krychu/llama

Thanks, this worked. 
<img width="286" alt="Screenshot 2023-07-28 at 7 31 41 AM" src="https://github.com/facebookresearch/llama/assets/97689901/de2c7025-30ac-4772-b4d2-74f1c6d5c576">

**Comment by tgvishal** [comment]
Getting this error:
I am using an M1 Mac(13-inch, M1, 2020) with 8GB RAM and 512 HDD:
I tried this: ` export PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0`, and the error stopped showing but I am not getting any response even I waited for 40 minutes:
`NOTE: Redirects are currently not supported in Windows or MacOs.
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
/Users/vishal/Documents/edumerge_work/AI/llama-v2-mps/llama/model.py:62: UserWarning: The operator 'aten::polar.out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
Loaded in 90.81 seconds`


Error Message:

```
(base) vishal@Vishals-MacBook-Pro llama-v2-mps % PYTORCH_ENABLE_MPS_FALLBACK=1 torchrun --nproc_per_node 1 example_text_completion.py \
    --ckpt_dir llama-2-7b/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 128 --max_batch_size 4

NOTE: Redirects are currently not supported in Windows or MacOs.
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
/Users/vishal/Documents/edumerge_work/AI/llama-v2-mps/llama/model.py:62: UserWarning: The operator 'aten::polar.out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
Traceback (most recent call last):
  File "/Users/vishal/Documents/edumerge_work/AI/llama-v2-mps/example_text_completion.py", line 55, in <module>
    fire.Fire(main)
  File "/Users/vishal/miniconda3/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vishal/miniconda3/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/vishal/miniconda3/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vishal/Documents/edumerge_work/AI/llama-v2-mps/example_text_completion.py", line 18, in main
    generator = Llama.build(
                ^^^^^^^^^^^^
  File "/Users/vishal/Documents/edumerge_work/AI/llama-v2-mps/llama/generation.py", line 113, in build
    model.to(device)
  File "/Users/vishal/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/vishal/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Users/vishal/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Users/vishal/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/Users/vishal/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/Users/vishal/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: MPS backend out of memory (MPS allocated: 8.91 GB, other allocations: 102.25 MB, max allowed: 9.07 GB). Tried to allocate 86.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 27101) of binary: /Users/vishal/miniconda3/bin/python
Traceback (most recent call last):
  File "/Users/vishal/miniconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/vishal/miniconda3/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/vishal/miniconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/Users/vishal/miniconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/Users/vishal/miniconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vishal/miniconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_text_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-12_16:31:07
  host      : 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 27101)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```
