### ISSUE TITLE
Error running `example_chat_completion.py` on `llama-2-7b-chat`

### ISSUE THREAD

**Issue by krsnnik** [facebookresearch/llama#430]
python 3.8 PyPi running on a nvidia rtx 3900

```
torchrun --nproc_per_node 1 example_chat_completion.py     --ckpt_dir llama-2-7b-chat/     --tokenizer_path tokenizer.model     --max_seq_len 512 --max_batch_size 4
```
```
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Loaded in 9.42 seconds
Traceback (most recent call last):
  File "example_chat_completion.py", line 73, in <module>
    fire.Fire(main)
  File "/home/kliu/Workspace/llama/env/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/kliu/Workspace/llama/env/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/kliu/Workspace/llama/env/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "example_chat_completion.py", line 56, in main
    results = generator.chat_completion(
  File "/home/kliu/Workspace/llama/llama/generation.py", line 270, in chat_completion
    generation_tokens, generation_logprobs = self.generate(
  File "/home/kliu/Workspace/llama/env/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/kliu/Workspace/llama/llama/generation.py", line 146, in generate
    next_token = sample_top_p(probs, top_p)
  File "/home/kliu/Workspace/llama/llama/generation.py", line 301, in sample_top_p
    next_token = torch.multinomial(probs_sort, num_samples=1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 155743) of binary: /home/kliu/Workspace/llama/env/bin/python3
Traceback (most recent call last):
  File "/home/kliu/Workspace/llama/env/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/kliu/Workspace/llama/env/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/kliu/Workspace/llama/env/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/kliu/Workspace/llama/env/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/kliu/Workspace/llama/env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kliu/Workspace/llama/env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-19_14:51:37
  host      : eleusis
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 155743)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

**Comment by zhpinkman** [comment]
I have the same issue. I tried reducing the batch_size, but it's not helping.

**Comment by jonsoku2** [comment]
I have the same issue.
```
$ pip install -e .

$ torchrun --nproc_per_node 1 example_chat_completion.py \                              at  08:09:59
    --ckpt_dir llama-2-7b-chat/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 512 --max_batch_size 4

NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "/Users/jp26710/Documents/GitHub/llama/example_chat_completion.py", line 73, in <module>
    fire.Fire(main)
  File "/opt/homebrew/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jp26710/Documents/GitHub/llama/example_chat_completion.py", line 20, in main
    generator = Llama.build(
                ^^^^^^^^^^^^
  File "/Users/jp26710/Documents/GitHub/llama/llama/generation.py", line 62, in build
    torch.distributed.init_process_group("nccl")
  File "/opt/homebrew/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1013, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 50237) of binary: /opt/homebrew/opt/python@3.11/bin/python3.11
Traceback (most recent call last):
  File "/opt/homebrew/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/opt/homebrew/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/homebrew/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-20_08:10:14
  host      : mCDX4PJQ2CR
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 50237)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by zhpinkman** [comment]
I could fix my issue using lower max_seq_len. hope this helps.

**Comment by jonsoku3** [comment]
> 

Thank you! what was your set max_seq_len ?

**Comment by zhpinkman** [comment]
I was using 512 that was throwing the error; with 256, it's working fine.

**Comment by jonsoku3** [comment]
Thank you. but It doesn't work for me :(
There seems to be a lot of related issues, so I'm watching this issue..!

**Comment by gucaslyz** [comment]
same error, and reduce max_seq_len to 128 not work.

**Comment by krsnnik** [comment]
Tried 128 as well and did not work, Also tried to reduce max_batch_size down to 1, also did not work, same `RuntimeError: probability tensor contains either inf, nan or element < 0` error

**Comment by nisargjoshi10** [comment]
Running into the same error. Tried changing batch size and max_seq_len but neither worked

**Comment by sthreepi** [comment]
Increasing the max_batch_size to >4 works. I set it to `6` and it works.
`torchrun --nproc_per_node 1 example_text_completion.py \
    --ckpt_dir llama-2-7b/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 128 --max_batch_size 1`

**Comment by maowenyu-11** [comment]
I've solved this error by setting the “max_batch_size” to a multiple of the number of prompts

**Comment by XanderDevelops** [comment]
Same error here, nothing seems to work

**Comment by prathams177** [comment]
i trying to run Llama3 model 8B got this issue - 

(llama3chatbot) C:\Users\prath\llama3-main>torchrun --nproc_per_node 1 example_chat_completion.py \ --ckpt_dir Meta-Llama-3-8B/ \ --tokenizer_path tokenizer
.model \ --max_seq_len 128 --max_batch_size 1
failed to create process.

it showing failed to process . whats  the issue ? help!!
