### ISSUE TITLE
Redirects are currently not supported in Windows or MacOs.

### ISSUE THREAD

**Issue by Crisfw** [facebookresearch/llama#497]
input：
torchrun --nproc_per_node 1 example_text_completion.py \
                                     --ckpt_dir llama-2-7b/ \
                                     --tokenizer_path tokenizer.model \
                                     --max_seq_len 128 --max_batch_size 4
outpuy:
Redirects are currently not supported in Windows or MacOs.
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [fw]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [fw]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [fw]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [fw]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
Traceback (most recent call last):
  File "C:\Users\youqi\llama\example_text_completion.py", line 55, in <module>
    fire.Fire(main)
  File "C:\Users\youqi\anaconda3\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\youqi\anaconda3\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\youqi\anaconda3\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\youqi\llama\example_text_completion.py", line 18, in main
    generator = Llama.build(
  File "C:\Users\youqi\llama\llama\generation.py", line 62, in build
    torch.distributed.init_process_group("nccl")
  File "C:\Users\youqi\anaconda3\lib\site-packages\torch\distributed\distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "C:\Users\youqi\anaconda3\lib\site-packages\torch\distributed\distributed_c10d.py", line 1013, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 12188) of binary: C:\Users\youqi\anaconda3\python.exe
Traceback (most recent call last):
  File "C:\Users\youqi\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\youqi\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\youqi\anaconda3\Scripts\torchrun.exe\__main__.py", line 7, in <module>
  File "C:\Users\youqi\anaconda3\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\youqi\anaconda3\lib\site-packages\torch\distributed\run.py", line 794, in main
    run(args)
  File "C:\Users\youqi\anaconda3\lib\site-packages\torch\distributed\run.py", line 785, in run
    elastic_launch(
  File "C:\Users\youqi\anaconda3\lib\site-packages\torch\distributed\launcher\api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\Users\youqi\anaconda3\lib\site-packages\torch\distributed\launcher\api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
example_text_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  rank      : 0 (local_rank: 0)
  exitcode  : 1
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by lonestarx1** [comment]
Facing the same issue

**Comment by ADD-eNavarro** [comment]
Same here.

**Comment by pzim-devdata** [comment]
I have solved it with a cpu installation by installing this : `https://github.com/krychu/llama` instead of `https://github.com/facebookresearch/llama`
Complete process to install : 
1. download the original version of Llama from : `https://github.com/facebookresearch/llama` and extract it to a `llama-main` folder
2. download th cpu version from : `https://github.com/krychu/llama` and extract it and replace files in the `llama-main` folder
3. run the `download.sh` script in a terminal, passing the URL provided when prompted to start the download
4. go to the `llama-main` folder
5. cretate an Python3 env : `python3 -m venv env` and activate it : `source env/bin/activate`
6. install the cpu version of pytorch : `python3 -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu #pour la version cpu`
7. install dependencies off llama : `python3 -m pip install -e .`
8. run if you have downloaded llama-2-7b : 
```
torchrun --nproc_per_node 1 example_text_completion.py \
    --ckpt_dir llama-2-7b/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 128 --max_batch_size 1 #(instead of 4)
```

**Comment by stephen-itschner** [comment]
NCCL isn't supported on windows. You can resolve this by editing line 62 in generation.py from "torch.distributed.init_process_group("nccl")" to "torch.distributed.init_process_group("gloo")"

You also will need to be sure you install MS visual studio, followed by CUDA (I got version 11.8), then a compatible pip installation for torch, by running something like "pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118"

**Comment by Crisfw** [comment]
thank you，I will try



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 29, 2023 10:37 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [facebookresearch/llama] Redirects are currently not supported inWindows or MacOs. (Issue #497)




 
NCCL isn't supported on windows. You can resolve this by editing line 62 in generation.py from "torch.distributed.init_process_group("nccl")" to "torch.distributed.init_process_group("gloo")"
 
You also will need to be sure you install MS visual studio, followed by CUDA (I got version 11.8), then a compatible pip installation for torch, by running something like "pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118"

**Comment by Crisfw** [comment]
Hello,I try it by your suggestion,but I still get error, can you give me more suggestion.
(base) C:\Users\youqi\llama&gt; torchrun --nproc_per_node 1 example_text_completion.py \&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;--ckpt_dir llama-2-7b/ \&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;--tokenizer_path tokenizer.model \&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; --max_seq_len 128 --max_batch_size 4
NOTE: Redirects are currently not supported in Windows or MacOs.
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [fw]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [fw]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [fw]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [fw]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
&gt; initializing model parallel with size 1
&gt; initializing ddp with size 1
&gt; initializing pipeline with size 1
Traceback (most recent call last):
&nbsp; File "C:\Users\youqi\llama\example_text_completion.py", line 55, in <module&gt;
&nbsp; &nbsp; fire.Fire(main)
&nbsp; File "C:\Users\youqi\anaconda3\lib\site-packages\fire\core.py", line 141, in Fire
&nbsp; &nbsp; component_trace = _Fire(component, args, parsed_flag_args, context, name)
&nbsp; File "C:\Users\youqi\anaconda3\lib\site-packages\fire\core.py", line 475, in _Fire
&nbsp; &nbsp; component, remaining_args = _CallAndUpdateTrace(
&nbsp; File "C:\Users\youqi\anaconda3\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
&nbsp; &nbsp; component = fn(*varargs, **kwargs)
&nbsp; File "C:\Users\youqi\llama\example_text_completion.py", line 18, in main
&nbsp; &nbsp; generator = Llama.build(
&nbsp; File "C:\Users\youqi\llama\llama\generation.py", line 93, in build
&nbsp; &nbsp; tokenizer = Tokenizer(model_path=tokenizer_path)
&nbsp; File "C:\Users\youqi\llama\llama\tokenizer.py", line 17, in __init__
&nbsp; &nbsp; assert os.path.isfile(model_path), model_path
AssertionError: tokenizer.model
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 6944) of binary: C:\Users\youqi\anaconda3\python.exe
Traceback (most recent call last):
&nbsp; File "C:\Users\youqi\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
&nbsp; &nbsp; return _run_code(code, main_globals, None,
&nbsp; File "C:\Users\youqi\anaconda3\lib\runpy.py", line 86, in _run_code
&nbsp; &nbsp; exec(code, run_globals)
&nbsp; File "C:\Users\youqi\anaconda3\Scripts\torchrun.exe\__main__.py", line 7, in <module&gt;
&nbsp; File "C:\Users\youqi\anaconda3\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 346, in wrapper
&nbsp; &nbsp; return f(*args, **kwargs)
&nbsp; File "C:\Users\youqi\anaconda3\lib\site-packages\torch\distributed\run.py", line 794, in main
&nbsp; &nbsp; run(args)
&nbsp; File "C:\Users\youqi\anaconda3\lib\site-packages\torch\distributed\run.py", line 785, in run
&nbsp; &nbsp; elastic_launch(
&nbsp; File "C:\Users\youqi\anaconda3\lib\site-packages\torch\distributed\launcher\api.py", line 134, in __call__
&nbsp; &nbsp; return launch_agent(self._config, self._entrypoint, list(args))
&nbsp; File "C:\Users\youqi\anaconda3\lib\site-packages\torch\distributed\launcher\api.py", line 250, in launch_agent
&nbsp; &nbsp; raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
example_text_completion.py FAILED
------------------------------------------------------------
Failures:
&nbsp; <NO_OTHER_FAILURES&gt;
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
&nbsp; time&nbsp; &nbsp; &nbsp; : 2023-08-05_17:38:55
&nbsp; host&nbsp; &nbsp; &nbsp; : fw
&nbsp; rank&nbsp; &nbsp; &nbsp; : 0 (local_rank: 0)
&nbsp; exitcode&nbsp; : 1 (pid: 6944)
&nbsp; error_file: <N/A&gt;
&nbsp; traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================





chriscut
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/llama"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月29日(星期六) 上午10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/llama] Redirects are currently not supported in Windows or MacOs. (Issue #497)





 
NCCL isn't supported on windows. You can resolve this by editing line 62 in generation.py from "torch.distributed.init_process_group("nccl")" to "torch.distributed.init_process_group("gloo")"
 
You also will need to be sure you install MS visual studio, followed by CUDA (I got version 11.8), then a compatible pip installation for torch, by running something like "pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118"

**Comment by Nightninja10** [comment]
> NCCL isn't supported on windows. You can resolve this by editing line 62 in generation.py from "torch.distributed.init_process_group("nccl")" to "torch.distributed.init_process_group("gloo")"
> 
> You also will need to be sure you install MS visual studio, followed by CUDA (I got version 11.8), then a compatible pip installation for torch, by running something like "pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118". All of this assumes you have a CUDA capable GPU and it is located at location 0.

i searched my whole machine for "generation.py" and came up with nothing. Still learning a bit about enviroments and setting this up. Can you help me understand why I wouldn't have this?

**Comment by Crisfw** [comment]
已收到邮件，我会尽快回信的

**Comment by difficulttopickaname** [comment]
Have you guys resolved it yet?

**Comment by Crisfw** [comment]
已收到邮件，我会尽快回信的

**Comment by Crisfw** [comment]
no，could you give me some advice?



---Original---
From: "Minhan ***@***.***&gt;
Date: Fri, Sep 22, 2023 09:29 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [facebookresearch/llama] Redirects are currently not supported inWindows or MacOs. (Issue #497)




 
Have you guys resolved it yet?

**Comment by difficulttopickaname** [comment]
Nah, I'm still stuck on the same problem. Either cuda out of memory, invalid address requested or redirects not supported. I will update if I find any solution.

**Comment by Crisfw** [comment]
ok，thank you



---Original---
From: "Minhan ***@***.***&gt;
Date: Fri, Sep 22, 2023 09:37 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [facebookresearch/llama] Redirects are currently not supported inWindows or MacOs. (Issue #497)




 
Nah, I'm still stuck on the same problem. Either cuda out of memory, invalid address requested or redirects not supported. I will update if I find any solution.
