### ISSUE TITLE
Unabel to run models on Windows

### ISSUE THREAD

**Issue by rashid-adobe** [facebookresearch/llama#527]
I have completed till the python installation after that when I am trying to execute pretrained-model https://github.com/facebookresearch/llama#pretrained-models then getting below error. Any idea how to fix this and run the models?
I am using **Windows 10** machine and have **Python 3.9.13**.

```
PS C:\git\llama> torchrun --nproc_per_node 1 example_chat_completion.py --ckpt_dir llama-2-7b --tokenizer_path tokenizer.model 
--max_seq_len 128 --max_batch_size 4
torchrun : The term 'torchrun' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ torchrun --nproc_per_node 1 example_chat_completion.py --ckpt_dir lla ...
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (torchrun:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\git\llama>
```

After that when I try to run with _python -m torch.distributed.run_ instead of _torchrun_ then getting below error.

```
PS C:\git\llama> python -m torch.distributed.run --nproc_per_node 1 example_text_completion.py --ckpt_dir llama-2-7b/ --tokenizer_path tokenizer.model --max_seq_len 128 --max_batch_size 4
NOTE: Redirects are currently not supported in Windows or MacOs.
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:29500 (system error: 10049 - The requested address is not valid 
in its context.).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:29500 (system error: 10049 - The requested address is not valid 
in its context.).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:29500 (system error: 10049 - The requested address is not valid 
in its context.).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:29500 (system error: 10049 - The requested address is not valid 
in its context.).
Traceback (most recent call last):
  File "C:\git\llama\example_text_completion.py", line 55, in <module>
    fire.Fire(main)
  File "C:\Users\mohammadr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\mohammadr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\mohammadr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\git\llama\example_text_completion.py", line 18, in main
    generator = Llama.build(
  File "C:\git\llama\llama\generation.py", line 62, in build
    torch.distributed.init_process_group("nccl")
  File "C:\Users\mohammadr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\distributed\distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "C:\Users\mohammadr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\distributed\distributed_c10d.py", line 1013, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 16920) of binary: C:\Users\mohammadr\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, 
in _run_code
    exec(code, run_globals)
  File "C:\Users\mohammadr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\distributed\run.py", line 798, in <module>
    main()
  File "C:\Users\mohammadr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\mohammadr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\distributed\run.py", line 794, in main
    run(args)
  File "C:\Users\mohammadr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\distributed\run.py", line 785, in run
    elastic_launch(
  File "C:\Users\mohammadr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\distributed\launcher\api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\Users\mohammadr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\distributed\launcher\api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
example_text_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-25_10:27:50
  host      : AB-CDEF123.xxx.xxxxx.com
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 16920)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
PS C:\git\llama> 
```

**Comment by pzim-devdata** [comment]
Yes it's a text completion so it will finish the sentence in the example_text_completion.py file which is "PyTorch is"... and the answer is : ..."a deep learning framework based on the Python programming language and the Torch library. It is widely used in machine learning, natural language processing, computer vision, and other fields. PyTorch is known for its flexibility, ease of use, and performance.
PyTorch is open source and available for free on"
Your sentence must be without a "#" (comment) before and "PyTorch is " --> #"PyTorch is "
I'm not running on Docker but perhaps you shouls update the file on Docker ...

**Comment by rashid-adobe** [comment]
I didn't find any text "PyTorch is" in file _example_text_completion.py_  or whole project. When I am chaing the prompt array value still I am getting the same "PyTorch is" response. Here is my file [example_text_completion](https://gist.github.com/RashidJorvee/78c590f8dce17e8570f0aa373e3471c3#file-example_text_completion-py).

**Comment by pzim-devdata** [comment]
Did you try to remove the file and see if you have the same answer ? In that case, you are not modifying the right file...

**Comment by rashid-adobe** [comment]
Yes, thank you!! I was updating the prompt in a wrong file and in command referrign a different file. Silly mistake.
