### ISSUE TITLE
How to solve it?

### ISSUE THREAD

**Issue by AIJIA000** [facebookresearch/llama#531]
torchrun --nproc_per_node 1 example_text_completion.py     --ckpt_dir llama-2-7b/     --tokenizer_path tokenizer.model     --max_seq_len 128 --max_batch_size 4
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "example_text_completion.py", line 55, in <module>
    fire.Fire(main)
  File "/root/anaconda3/envs/lla/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/anaconda3/envs/lla/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/anaconda3/envs/lla/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "example_text_completion.py", line 18, in main
    generator = Llama.build(
  File "/root/code/llama/llama_v2/llama/generation.py", line 93, in build
    tokenizer = Tokenizer(model_path=tokenizer_path)
  File "/root/code/llama/llama_v2/llama/tokenizer.py", line 18, in __init__
    self.sp_model = SentencePieceProcessor(model_file=model_path)
  File "/root/anaconda3/envs/lla/lib/python3.8/site-packages/sentencepiece/__init__.py", line 447, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "/root/anaconda3/envs/lla/lib/python3.8/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/root/anaconda3/envs/lla/lib/python3.8/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: unk is not defined.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3596437) of binary: /root/anaconda3/envs/lla/bin/python
Traceback (most recent call last):
  File "/root/anaconda3/envs/lla/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/root/anaconda3/envs/lla/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/anaconda3/envs/lla/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/root/anaconda3/envs/lla/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/anaconda3/envs/lla/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/anaconda3/envs/lla/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
example_text_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-25_14:29:19
  host      : suanligpu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3596437)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

I checked many methods to solve this problem.

**Comment by pzim-devdata** [comment]
same : torch.distributed.elastic.multiprocessing.errors.ChildFailedError

**Comment by pzim-devdata** [comment]
I have solved it with a cpu installation by installing this : `https://github.com/krychu/llama` instead of `https://github.com/facebookresearch/llama`
Complete process to install : 
1. download the cpu version from : `https://github.com/facebookresearch/llama/` and extract it to a `llama-main` folder
2. run the `download.sh` script in a terminal, passing the URL provided when prompted to start the download
3. go to the `llama-main` folder
4. cretate an Python3 env : `python3 -m venv env` and activate it : `source env/bin/activate`
5. install the cpu version of pytorch : `python3 -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu #pour la version cpu`
6. install dependencies off llama : `python3 -m pip install -e .`
7. run if you have downloaded llama-2-7b : 
```
torchrun --nproc_per_node 1 example_text_completion.py \
    --ckpt_dir llama-2-7b/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 128 --max_batch_size 1 #(instead of 4)
```

**Comment by ttkrpink** [comment]
Try this. It seems the tokenizer.model is empty after one day.
The following solution works for me.

https://github.com/facebookresearch/llama/issues/287#issuecomment-1645272041

**Comment by ujjwalkarn** [comment]
Closing since the solution in https://github.com/facebookresearch/llama/issues/287#issuecomment-1645272041 should work - please reopen if it does not.
