### ISSUE TITLE
AssertionError: Loading a checkpoint for MP=1 but world size is 4

### ISSUE THREAD

**Issue by Cxm211** [facebookresearch/llama#551]
I tried to run llama-2-7b on 4 GPUs by running torchrun --nproc_per_node 4 example_text_completion.py \
    --ckpt_dir llama-2-7b/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 128 --max_batch_size 1
But I got the error: AssertionError: Loading a checkpoint for MP=1 but world size is 4

**Comment by Cxm211** [comment]
> have you tried changing max_batch_size to 4?

Yes. It gave me the same error.

**Comment by Cxm211** [comment]
> initializing model parallel with size 4
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "/common/home/users/x/xuemengcai/llama/example_text_completion.py", line 55, in <module>
Traceback (most recent call last):
  File "/common/home/users/x/xuemengcai/llama/example_text_completion.py", line 55, in <module>
    fire.Fire(main)
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
Traceback (most recent call last):
  File "/common/home/users/x/xuemengcai/llama/example_text_completion.py", line 55, in <module>
Traceback (most recent call last):
  File "/common/home/users/x/xuemengcai/llama/example_text_completion.py", line 55, in <module>
    fire.Fire(main)
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
    component_trace = _Fire(component, args, parsed_flag_args, context, name)  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire

  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component, remaining_args = _CallAndUpdateTrace(
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    fire.Fire(main)
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component = fn(*varargs, **kwargs)
  File "/common/home/users/x/xuemengcai/llama/example_text_completion.py", line 18, in main
    component = fn(*varargs, **kwargs)
  File "/common/home/users/x/xuemengcai/llama/example_text_completion.py", line 18, in main
    generator = Llama.build(
  File "/common/home/users/x/xuemengcai/llama/llama/generation.py", line 80, in build
    generator = Llama.build(
  File "/common/home/users/x/xuemengcai/llama/llama/generation.py", line 80, in build
    component, remaining_args = _CallAndUpdateTrace(
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    assert model_parallel_size == len(
AssertionError: Loading a checkpoint for MP=1 but world size is 4
    assert model_parallel_size == len(
AssertionError: Loading a checkpoint for MP=1 but world size is 4
    component = fn(*varargs, **kwargs)
  File "/common/home/users/x/xuemengcai/llama/example_text_completion.py", line 18, in main
    generator = Llama.build(
  File "/common/home/users/x/xuemengcai/llama/llama/generation.py", line 80, in build
    assert model_parallel_size == len(
AssertionError: Loading a checkpoint for MP=1 but world size is 4
    fire.Fire(main)
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/common/home/users/x/xuemengcai/llama/example_text_completion.py", line 18, in main
    generator = Llama.build(
  File "/common/home/users/x/xuemengcai/llama/llama/generation.py", line 80, in build
    assert model_parallel_size == len(
AssertionError: Loading a checkpoint for MP=1 but world size is 4
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 404335) of binary: /common/home/users/x/xuemengcai/.conda/envs/finetune/bin/python
Traceback (most recent call last):
  File "/common/home/users/x/xuemengcai/.conda/envs/finetune/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_text_completion.py FAILED

**Comment by Cxm211** [comment]
> initializing model parallel with size 4
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "/common/home/users/x/xuemengcai/llama/example_text_completion.py", line 55, in <module>
Traceback (most recent call last):
  File "/common/home/users/x/xuemengcai/llama/example_text_completion.py", line 55, in <module>
    fire.Fire(main)
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
Traceback (most recent call last):
  File "/common/home/users/x/xuemengcai/llama/example_text_completion.py", line 55, in <module>
Traceback (most recent call last):
  File "/common/home/users/x/xuemengcai/llama/example_text_completion.py", line 55, in <module>
    fire.Fire(main)
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
    component_trace = _Fire(component, args, parsed_flag_args, context, name)  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire

  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component, remaining_args = _CallAndUpdateTrace(
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    fire.Fire(main)
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component = fn(*varargs, **kwargs)
  File "/common/home/users/x/xuemengcai/llama/example_text_completion.py", line 18, in main
    component = fn(*varargs, **kwargs)
  File "/common/home/users/x/xuemengcai/llama/example_text_completion.py", line 18, in main
    generator = Llama.build(
  File "/common/home/users/x/xuemengcai/llama/llama/generation.py", line 80, in build
    generator = Llama.build(
  File "/common/home/users/x/xuemengcai/llama/llama/generation.py", line 80, in build
    component, remaining_args = _CallAndUpdateTrace(
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    assert model_parallel_size == len(
AssertionError: Loading a checkpoint for MP=1 but world size is 4
    assert model_parallel_size == len(
AssertionError: Loading a checkpoint for MP=1 but world size is 4
    component = fn(*varargs, **kwargs)
  File "/common/home/users/x/xuemengcai/llama/example_text_completion.py", line 18, in main
    generator = Llama.build(
  File "/common/home/users/x/xuemengcai/llama/llama/generation.py", line 80, in build
    assert model_parallel_size == len(
AssertionError: Loading a checkpoint for MP=1 but world size is 4
    fire.Fire(main)
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/common/home/users/x/xuemengcai/llama/example_text_completion.py", line 18, in main
    generator = Llama.build(
  File "/common/home/users/x/xuemengcai/llama/llama/generation.py", line 80, in build
    assert model_parallel_size == len(
AssertionError: Loading a checkpoint for MP=1 but world size is 4
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 404335) of binary: /common/home/users/x/xuemengcai/.conda/envs/finetune/bin/python
Traceback (most recent call last):
  File "/common/home/users/x/xuemengcai/.conda/envs/finetune/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/common/home/users/x/xuemengcai/.local/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
example_text_completion.py FAILED

**Comment by yash-s20** [comment]
https://github.com/facebookresearch/llama/issues/40

has it anything to do with this error?
If not i'll try reproducing your error.


Also, what model are you loading from? I don't know if its a requirement but was that model trained on 4 nodes?

**Comment by Cxm211** [comment]
I download llama-2-7b using download.sh script

**Comment by bronzafa** [comment]
Have you tried  --nproc_per_node 1? using it the result is this:
llama# torchrun --nproc_per_node 1 chat.py     --ckpt_dir llama-2-7b-chat/     --tokenizer_path tokenizer.model     --max_seq_len 800 --max_batch_size 1
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
and work fine

**Comment by Cxm211** [comment]
Yes,

> Have you tried --nproc_per_node 1? using it the result is this: llama# torchrun --nproc_per_node 1 chat.py --ckpt_dir llama-2-7b-chat/ --tokenizer_path tokenizer.model --max_seq_len 800 --max_batch_size 1
> 
> > initializing model parallel with size 1
> > initializing ddp with size 1
> > initializing pipeline with size 1
> > and work fine

It works! Thank you so much for your help!

**Comment by Modas-Li** [comment]
but i came across "out of memory" when loading with single A100

**Comment by bronzafa** [comment]
can you post the error and the command you are using?
