### ISSUE TITLE
AssertionError: no checkpoint files found in llama-2-7b

### ISSUE THREAD

**Issue by vanjy-eng** [facebookresearch/llama#577]
Hello, I'm trying to run llama2-7b text completion
```
torchrun --nproc_per_node 1 example_text_completion.py \
>     --ckpt_dir llama-2-7b/ \
>     --tokenizer_path tokenizer.model \
>     --max_seq_len 128 --max_batch_size 4
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
```
and I get the below error.

```
Traceback (most recent call last):
  File "example_text_completion.py", line 55, in <module>
    fire.Fire(main)
  File "/home/tech/venv/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/tech/venv/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/tech/venv/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "example_text_completion.py", line 18, in main
    generator = Llama.build(
  File "/home/tech/llama/llama/generation.py", line 79, in build
    assert len(checkpoints) > 0, f"no checkpoint files found in {ckpt_dir}"
AssertionError: no checkpoint files found in llama-2-7b/
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 12729) of binary: /home/tech/venv/bin/python3.8
Traceback (most recent call last):
  File "/home/tech/venv/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/tech/venv/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/tech/venv/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/tech/venv/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/tech/venv/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/tech/venv/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_text_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-28_14:59:33
  host      : llama2-instance-1.us-central1-a.c.kera-internship.internal
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 12729)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

All model downloads were successful
Any help will be appreciated.

**Comment by vanjy-eng** [comment]
solved. I had git cloned into a folder I named llama. So I had two llama folders and was sitting within the second llama folder while trying to run the example_text_completion.py file. So I had to cd out of all folders to allow me to run.

```
torchrun --nproc_per_node 1 llama/example_text_completion.py \
>     --ckpt_dir llama-2-7b/ \
>     --tokenizer_path tokenizer.model \
>     --max_seq_len 128 --max_batch_size 4
```

**Comment by MINJIK01** [comment]
> Hello I got exactly the same Error message. How did you deal with that problem. In my case I even couldn't find checkpoint file anywhere.

It was because of my google drive capacity. I solved.

**Comment by AdyelAhmed** [comment]
torchrun --nproc_per_node 1 example_chat_completion.py --ckpt_dir "D:\Llama 3\CodeLlama-7b\consolidated.00.pth" --tokenizer_path "D:\Llama 3\CodeLlama-7b\tokenizer.model" --max_seq_len 512 --max_batch_size 6

i am using the above command and getting the same error. can someone please help.

**Comment by Eyesun23** [comment]
I am  getting  the  same error as well
