### ISSUE TITLE
Redirects are currently not supported in Windows or MacOs.

### ISSUE THREAD

**Issue by YinhaoDeng** [facebookresearch/llama#592]
# I am using Anaconda Environment on Windows, GPU-enabled Pytorch.

Error message starts here:

(pytorch) PS C:\Users\yinha\OneDrive\Desktop\llama-main> torchrun --nproc_per_node 1 example_text_completion.py --ckpt_dir llama-2-7b/ --tokenizer_path tokenizer.model --max_seq_len 128 --max_batch_size 4
NOTE: Redirects are currently not supported in Windows or MacOs.
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [Yinhao]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [Yinhao]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [Yinhao]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [Yinhao]:29500 (system error: 10049 - The requested address is not valid in its context.).
Traceback (most recent call last):
  File "C:\Users\yinha\OneDrive\Desktop\llama-main\example_text_completion.py", line 55, in <module>
    torch.distributed.init_process_group("nccl")  # original
  File "C:\Users\yinha\.conda\envs\pytorch\lib\site-packages\torch\distributed\distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "C:\Users\yinha\.conda\envs\pytorch\lib\site-packages\torch\distributed\distributed_c10d.py", line 1013, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 31372) of binary: C:\Users\yinha\.conda\envs\pytorch\python.exe
Traceback (most recent call last):
  File "C:\Users\yinha\.conda\envs\pytorch\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\yinha\.conda\envs\pytorch\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\yinha\.conda\envs\pytorch\Scripts\torchrun.exe\__main__.py", line 7, in <module>
  File "C:\Users\yinha\.conda\envs\pytorch\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\yinha\.conda\envs\pytorch\lib\site-packages\torch\distributed\run.py", line 794, in main
    run(args)
  File "C:\Users\yinha\.conda\envs\pytorch\lib\site-packages\torch\distributed\run.py", line 785, in run
    elastic_launch(
  File "C:\Users\yinha\.conda\envs\pytorch\lib\site-packages\torch\distributed\launcher\api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\Users\yinha\.conda\envs\pytorch\lib\site-packages\torch\distributed\launcher\api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
example_text_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-31_17:34:37
  host      : Yinhao.home
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 31372)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by FahadQuait** [comment]
have you managed to fix the issue>

**Comment by YinhaoDeng** [comment]
> have you managed to fix the issue?

Note yet bro @FahadQuait

**Comment by kechan** [comment]
I tried on M2 Mac, got an error but slightly different than @YinhaoDeng. 

Not sure if somewhere, the device need to be set to "mps" since my macbook doesn't have CUDA.

(python310_env) llama % torchrun --nproc_per_node 1 example_chat_completion.py --ckpt_dir llama-2-7b-chat --tokenizer_path tokenizer.model --max_qen_len 128 --max_batch_size 4
NOTE: Redirects are currently not supported in Windows or MacOs.
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  ... 
 ... 
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

  File ".../site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "..//site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File ".../site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "..../site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File ".../site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by HawkingRadiation42** [comment]
facing the same issue here as well, if anyone here has found a fix then do share.

**Comment by kechan** [comment]
for Mac, lot of ppl either ran it with the integration with huggingface, or llama2.cpp on quantized or half-precision version. But I am just curious if it can be made to run on my Macbook with raw llama2 direct from Facebook. I am still hitting issues 1 after another making changes here/there I thought should be sensible. If anyone managed to get this to run, however slow, please do share. I have 96gb, so maybe I can run the 7B chat at half precision (dunno).

**Comment by kikitaMoon** [comment]
facing same issue here

**Comment by thewbuk** [comment]
I managed to run it with hugging face

**Comment by donhui** [comment]
facing same issue here

**Comment by kikitaMoon** [comment]
I finally downloaded the model from hugging face and run it successfully on Windows 10.

**Comment by JeffLiu114514** [comment]
Is the only way to solve this downloading model from hugging face?

**Comment by thewbuk** [comment]
> huggingface, you means this https://huggingface.co/meta-llama/Llama-2-7b-hf or this https://huggingface.co/meta-llama/Llama-2-7b?

https://huggingface.co/meta-llama/Llama-2-7b-hf

**Comment by choiking** [comment]
> > huggingface, you means this https://huggingface.co/meta-llama/Llama-2-7b-hf or this https://huggingface.co/meta-llama/Llama-2-7b?
> 
> https://huggingface.co/meta-llama/Llama-2-7b-hf
thanks.

should we also replace the Llama-2-7b-chat with hf?
