### ISSUE TITLE
ModuleNotFoundError: No module named 'fairscale'

### ISSUE THREAD

**Issue by atigm** [facebookresearch/llama#595]
Macbook pro:
2,3 GHz Intel Core i7 - 4 cores
16 Go 3733 MHz LPDDR4X 
Intel Iris Plus Graphics 1536 Mo

All requirements are installed:
```
...
Requirement already satisfied: torch in ./env/lib/python3.9/site-packages (from llama==0.0.1) (2.0.1)
Requirement already satisfied: fairscale in ./env/lib/python3.9/site-packages (from llama==0.0.1) (0.4.13)
Requirement already satisfied: fire in ./env/lib/python3.9/site-packages (from llama==0.0.1) (0.5.0)
...
```

When I run 
 ```
torchrun --nproc_per_node 1 example_text_completion.py \                                                                 
    --ckpt_dir llama-2-7b/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 128 --max_batch_size 1
```

I have:

```
NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "/Users/dev/llama/llama/example_text_completion.py", line 6, in <module>
    from llama import Llama
  File "/Users/dev/llama/llama/llama/__init__.py", line 4, in <module>
    from .generation import Llama
  File "/Users/dev/llama/llama/llama/generation.py", line 14, in <module>
    from fairscale.nn.model_parallel.initialize import (
ModuleNotFoundError: No module named 'fairscale'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 88389) of binary: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_text_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-31_15:52:54
  host      : 82.1.168.192.in-addr.arpa
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 88389)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
==
```

Thank you

**Comment by atigm** [comment]
installation error

**Comment by safridisiterx** [comment]
Having this exact issue--what was wrong with your initial installation?

**Comment by cshang2017** [comment]
check torchrun 
if the top line python points to correct python path.

**Comment by Harsh-raj** [comment]
i am getting "ModuleNotFoundError: No module named 'fire'", while attempting to run the example_text_completion.py file for llama-2-7b-chat model. I have installed it with pip but it keeps throwing same error. Where am i going wrong
