### ISSUE TITLE
closing signal SIGTERM

### ISSUE THREAD

**Issue by atigm** [facebookresearch/llama#603]
I use AWS c5.4xlarge (32G RAM and 16 vCPU) instance.
7B work fine.
But 13B and 13B-chat I have a problem.

When I run:
```
torchrun --nproc_per_node 2 example_text_completion.py \
    --ckpt_dir llama-2-13b/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 512 --max_batch_size 4
```
   
I have this error:

```
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
> initializing model parallel with size 2
> initializing ddp with size 1
> initializing pipeline with size 1
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1796 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 1795) of binary: /home/ubuntu/llama2/env/bin/python3
Traceback (most recent call last):
  File "/home/ubuntu/llama2/env/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/llama2/env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/llama2/env/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/ubuntu/llama2/env/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/ubuntu/llama2/env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/llama2/env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
example_text_completion.py FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-01_12:17:04
  host      : ip-172-31-90-33.ec2.internal
  rank      : 0 (local_rank: 0)
  exitcode  : -9 (pid: 1795)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 1795
```

Thank you

**Comment by kaolin** [comment]
It's likely a CPU OOM issue — the model gets loaded into CPU before being transferred to GPU, so if you're doing it with a docker or with something else constraining the CPU memory, it's likely to be getting killed for that. (feel free to re-open if this isn't the issue). Similar topic: https://discuss.huggingface.co/t/torch-distributed-elastic-multiprocessing-errors-childfailederror/28242/13
