### ISSUE TITLE
AWS G4dn : no GPUs found!

### ISSUE THREAD

**Issue by atigm** [facebookresearch/llama#636]
I run `torchrun --nproc_per_node 1 example_text_completion.py     --ckpt_dir llama-2-7b/     --tokenizer_path tokenizer.model     --max_seq_len 128 --max_batch_size 4`
I use AWS G4ad instance (g4dn.4xlarge) : 16 vCPU and 64GB) 
G4dn instances feature NVIDIA T4 GPUs and custom Intel Cascade Lake CPUs, and are optimized for machine learning inference and small scale training : https://aws.amazon.com/fr/ec2/instance-types/g4/

But I still have: `RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!`

the full logs:

```
============================================================
(env) ubuntu@ip-172-31-2-39:~/llama-fb$ torchrun --nproc_per_node 1 example_text_completion.py     --ckpt_dir llama-2-7b/     --tokenizer_path tokenizer.model     --max_seq_len 128 --max_batch_size 4
Traceback (most recent call last):
  File "/home/ubuntu/llama-fb/example_text_completion.py", line 55, in <module>
    fire.Fire(main)
  File "/home/ubuntu/llama-fb/env/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ubuntu/llama-fb/env/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/ubuntu/llama-fb/env/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ubuntu/llama-fb/example_text_completion.py", line 18, in main
    generator = Llama.build(
  File "/home/ubuntu/llama-fb/llama/generation.py", line 58, in build
    torch.distributed.init_process_group("nccl")
  File "/home/ubuntu/llama-fb/env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "/home/ubuntu/llama-fb/env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1024, in _new_process_group_helper
    backend_class = ProcessGroupNCCL(backend_prefix_store, group_rank, group_size, pg_options)
RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 12105) of binary: /home/ubuntu/llama-fb/env/bin/python3
Traceback (most recent call last):
  File "/home/ubuntu/llama-fb/env/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/llama-fb/env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/llama-fb/env/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/ubuntu/llama-fb/env/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/ubuntu/llama-fb/env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/llama-fb/env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_text_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-07_12:54:04
  host      : ip-172-31-12-49.us-west-2.compute.internal
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 12105)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by zeelsheladiya** [comment]
**Check GPU Availability**: Confirm that the GPUs are recognized and available on your instance. You can use the nvidia-smi command to check the GPU status.
```
nvidia-smi
```

**CUDA and cuDNN**: Ensure that you have the appropriate version of CUDA and cuDNN installed on your instance. The Llama 2 models likely require specific versions of CUDA and cuDNN to work properly.
```
nvcc --version
```

**Environment Variables**: Check if you have the necessary environment variables set correctly for CUDA and cuDNN. These variables are often required for proper GPU usage. 
```
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
export CUDA_HOME=/usr/local/cuda
```

Double-check the command you're using to execute the script. 
```
torchrun --nproc_per_node 1 python example_text_completion.py --ckpt_dir llama-2-7b/ --tokenizer_path tokenizer.model --max_seq_len 128 --max_batch_size 4
```

**Driver and Package Versions**: Make sure you have the correct versions of PyTorch, CUDA, and other required packages installed. Incompatibilities between different package versions can sometimes lead to such errors.

**Instance Configuration**: Ensure that your AWS G4ad instance is properly configured to use GPUs. Double-check the instance settings and verify that GPU resources are allocated to the instance.

**GPU Permissions**: In some cases, GPU access might require appropriate permissions. Ensure that your user has the necessary permissions to access and utilize the GPU resources.

**Restart the Instance**: If you've made changes to the instance configuration, CUDA, or environment variables, consider restarting the instance to ensure that the changes take effect.
