### ISSUE TITLE
In meta-llama/Llama-2-7b-hf i got issue after staring fine tunning is that ValueError: `do_sample` is set to `False`. However, temperature is set to 0.9 -- this flag is only used in sample-based generation modes. Set `do_sample=True` or unset temperature to continue.

### ISSUE THREAD

**Issue by Hiren838** [facebookresearch/llama#649]
2023-08-09 07:06:00.709891: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
> INFO    Running LLM
> INFO    Params: Namespace(version=False, train=True, deploy=False, inference=False, data_path='/content/drive/MyDrive/conference_paper/', train_split='train', valid_split=None, text_column='text', model='meta-llama/Llama-2-7b-hf', learning_rate=0.0002, num_train_epochs=3, train_batch_size=4, eval_batch_size=4, warmup_ratio=0.1, gradient_accumulation_steps=1, optimizer='adamw_torch', scheduler='linear', weight_decay=0.0, max_grad_norm=1.0, seed=42, add_eos_token=False, block_size=-1, use_peft=True, lora_r=16, lora_alpha=32, lora_dropout=0.05, training_type='generic', train_on_inputs=False, logging_steps=-1, project_name='my-chat', evaluation_strategy='epoch', save_total_limit=1, save_strategy='epoch', auto_find_batch_size=False, fp16=False, push_to_hub=True, use_int8=False, model_max_length=2048, repo_id='hiren838/Student_support_sysytem', use_int4=True, trainer='sft', target_modules=None, func=<function run_llm_command_factory at 0x7a4a6ee34430>)
> INFO    loading dataset from csv
Using pad_token, but it is not set yet.
Loading checkpoint shards: 100% 2/2 [01:14<00:00, 37.10s/it]
Traceback (most recent call last):
  File "/usr/local/bin/autotrain", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 36, in main
    command.run()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/run_llm.py", line 409, in run
    train_llm(params)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm.py", line 115, in train
    model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2971, in from_pretrained
    model.generation_config = GenerationConfig.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py", line 689, in from_pretrained
    return cls.from_dict(config_dict, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py", line 722, in from_dict
    config = cls(**{**config_dict, **kwargs})
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py", line 316, in __init__
    self.validate()
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py", line 354, in validate
    raise ValueError(
ValueError: `do_sample` is set to `False`. However, temperature is set to 0.9 -- this flag is only used in sample-based generation modes. Set `do_sample=True` or unset temperature to continue. 

"Even there is no parameter in autotrain called do_sample and temperature "

**Comment by Hiren838** [comment]
> For anyone looking for a solution, it was an issue with the latest release of hugging face transformers released recently. Please downgrade to the previous version !pip install git+https://github.com/huggingface/transformers@v4.31-release to fix the issue.

Thank You. It worked
