### ISSUE TITLE
torch.distributed.elastic.multiprocessing.errors.ChildFailedError

### ISSUE THREAD

**Issue by darek-ai** [facebookresearch/llama#721]
OS: ubunt 
8 vCPU 32 GiB
GPU：NVIDIA V100  

root@iZwz98etw3xqaylir1y6pjZ:~/llama# nvidia-smi
Sat Aug 26 17:02:01 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:07.0 Off |                    0 |
| N/A   32C    P0    40W / 300W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

root@iZwz98etw3xqaylir1y6pjZ:~/llama# torchrun --nproc_per_node 1 example_text_completion.py --ckpt_dir llama-2-7b-chat/ --tokenizer_path tokenizer.model --max_seq_len 512 --max_batch_size 4
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "/root/llama/example_text_completion.py", line 55, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/llama/example_text_completion.py", line 18, in main
    generator = Llama.build(
  File "/root/llama/llama/generation.py", line 83, in build
    checkpoint = torch.load(ckpt_path, map_location="cpu")
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1727) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
example_text_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-26_16:58:22
  host      : iZwz98etw3xqaylir1y6pjZ
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1727)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by EmanuelaBoros** [comment]
It seems that it cannot load the model correctly that should be in llama-2-7b-chat/. Can you check if you properly downloaded it?

**Comment by bikekowal** [comment]
Experienced the same issue.

**Comment by gzk-x64** [comment]
### Getting logs
I found on another post that by adding '`from torch.distributed.elastic.multiprocessing.errors import record`' at the beginning of the Python file being used (in my case, "`example_completion.py`") and then adding "`@record`" just above "`def main(`", critical errors were logged in kern.log. In my case (WSL 2), they are stored in `/var/log/kern.log`, but I believe this varies depending on the distribution.

### Out of RAM
I came across a message that suggested that I had run out of memory and that the process responsible for clearing the RAM had taken over. As a result, the torch process was naturally crashing. 

I identified that WSL 2 allocates - by default - half of the host's RAM to the Linux subsystem. In my case, with 16GB of RAM, this means 8GB for Linux. In my **Windows home directory**, I created the "`.wslconfig`" file and added the following:
```
    [wsl2]
    memory=14GB
```
This allowed for more RAM to be allocated to the VM (this can be observed by using the "top" command, for example).

### New error
Now the issue I have is different: when I launch the command, it quickly consumes all my host's RAM (I observe it in real-time using the Windows Task Manager) and crashes with a new error message:
    "`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 8.00 GiB total capacity; 7.23 GiB already allocated; 0 bytes free; 7.24 GiB reserved in total by PyTorch). If reserved memory is significantly greater than allocated memory, try setting max_split_size_mb to avoid fragmentation. See the documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF.`"
    
I don't understand why the error message mentions my GPU (which is not being utilized at all during loading as far as I can see in the task manager), while it's the RAM that is full.

### Hypothesis

I'm surprised; I thought the llama 7b model was supposed to require less RAM. I'm a bit confused now whether I actually have a real RAM shortage problem, or if it's the llama code that consumes more, or if there's a configuration issue somewhere.

**Comment by EmanuelaBoros** [comment]
@darek-ai What are the sizes of the files also?

**Comment by kucukagan** [comment]
I take same error.. I have some folder above.. I have 2Tb hard disk size and nvidia-4080.

**Comment by WangYangfan** [comment]
i meet the same error, and i solved it by redownload some files. Maybe you shoud check your following files if their size is 0KB.
- llama-2-7b-chat/checklist.chk
- llama-2-7b-chat/consolidated.00.pth
- llama-2-7b-chat/params.json
- tokenizer.model
- tokenizer_checklist.chk

After redownload, these problems might be solved.

**Comment by ithllc** [comment]
Currently, I am getting the exact same error. Trying to run it on 2TB disk, 64GB Ram, WSL2 Ubuntu 22.04, Python 3.11.1, with PyTorch 2 and cuda 11.8.  GPU is Nvidia GeForce GTX 1650 Ti. All code is in the folder structures and I am specifically running this from the example for "CodeLlama-7b-Instruct".  My folder structure does not look like what is previously spoken of above, but I am only trying to run Code Llama2. My files are listed in my Code Llama2 folder structures, just as listed as above with sizes of 92k for the files.  Any suggestions would be helpful.

**Comment by Harsh-raj** [comment]
When I attempt to run example python script using the command `torchrun --nproc_per_node 1 example_text_completion.py --ckpt_dir llama-2-7b-chat/ --tokenizer_path tokenizer.model --max_seq_len 512 --max_batch_size 4` i am getting ModuleNotFoundError: No module named 'fire', i have fire installed i am using remote server for GPUs. How can i resolve this issue.

**Comment by EmanuelaBoros** [comment]
@Harsh-raj When you execute `torchrun`, it means `python -m torch.distributed.launch ..`, thus it uses the first version of python it finds (might be an env, might be the one installed in the system). You should check how many python version you have installed or if you have or have not activated an env - and if you've actually installed `fire` in the correct python.
