### ISSUE TITLE
RuntimeError: Distributed package doesn't have NCCL built in

### ISSUE THREAD

**Issue by jclega** [facebookresearch/llama#722]
Using macos getting this error when executing : torchrun --nproc_per_node 1 example_text_completion.py \ --ckpt_dir llama-2-7b/ \--tokenizer_path tokenizer.model \ --max_seq_len 128 --max_batch_size 4

Error : NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "/Users/jc/Downloads/tworobins/llama/llama-main/example_text_completion.py", line 55, in <module>
    fire.Fire(main)
  File "/Users/jc/miniconda3/envs/myenv/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/jc/miniconda3/envs/myenv/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/jc/miniconda3/envs/myenv/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/jc/Downloads/tworobins/llama/llama-main/example_text_completion.py", line 18, in main
    generator = Llama.build(
  File "/Users/jc/Downloads/tworobins/llama/llama-main/llama/generation.py", line 62, in build
    torch.distributed.init_process_group("nccl")
  File "/Users/jc/miniconda3/envs/myenv/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "/Users/jc/miniconda3/envs/myenv/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1013, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 23024) of binary: /Users/jc/miniconda3/envs/myenv/bin/python
Traceback (most recent call last):
  File "/Users/jc/miniconda3/envs/myenv/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/Users/jc/miniconda3/envs/myenv/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/_init_.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/Users/jc/miniconda3/envs/myenv/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/Users/jc/miniconda3/envs/myenv/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/Users/jc/miniconda3/envs/myenv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in _call_
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/Users/jc/miniconda3/envs/myenv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_text_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-26_15:15:15
  host      : 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 23024)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by EmanuelaBoros** [comment]
Try this solution: https://github.com/facebookresearch/llama/issues/699#issuecomment-1688777017

**Comment by albertodepaola** [comment]
Hi @jclega, we currently don't support macos for Llama, but the community has put forth some great projects that do support mac and some cloud resources are available for free.

**Comment by TimYao18** [comment]
I think the llama support platforms should list on the README.md.
And is there planning to support macOS?
