### ISSUE TITLE
"Distributed package doesn't have NCCL built in" error in Centos 7 with NVIDIA Tesla K80

### ISSUE THREAD

**Issue by syunusic** [facebookresearch/llama#734]
I'm trying to run the example in a Linux Centos 7.9 with NVIDIA Tesla K80 running (not MacOS!!):
```
# nvidia-smi
Mon Aug 28 17:49:02 2023      
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.199.02   Driver Version: 470.199.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:84:00.0 Off |                    0 |
| N/A   43C    P0    66W / 149W |      0MiB / 11441MiB |     97%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00000000:85:00.0 Off |                    0 |
| N/A   36C    P0    71W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```
Whe I run the example this is the error I've got:

```
# torchrun --nproc_per_node 1 example_chat_completion.py     --ckpt_dir llama-2-7b-chat/     --tokenizer_path tokenizer.model     --max_seq_len 512 --max_batch_size 6
Traceback (most recent call last):
  File "/root/llama/example_chat_completion.py", line 89, in <module>
    fire.Fire(main)
  File "/usr/local/bin/anaconda3/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/anaconda3/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/anaconda3/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/llama/example_chat_completion.py", line 20, in main
    generator = Llama.build(
                ^^^^^^^^^^^^
  File "/root/llama/llama/generation.py", line 61, in build
    torch.distributed.init_process_group("nccl")
  File "/usr/local/bin/anaconda3/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/anaconda3/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1013, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2591) of binary: /usr/local/bin/anaconda3/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/anaconda3/bin/torchrun", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/bin/anaconda3/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/anaconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/bin/anaconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/bin/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-28_17:50:10
  host      : tyrion.dalmacia.local
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2591)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```
I even installed NCCL manually (yum) :
```
yum install libnccl-2.18.3-1+cuda11.0 libnccl-devel-2.18.3-1+cuda11.0 libnccl-static-2.18.3-1+cuda11.0
```

I followed all instructions [from here](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html). Due I have K80, I had to install [cuda-drivers-470.199.02-1.x86_64.rpm](https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-drivers-470.199.02-1.x86_64.rpm). No luck.

Any ideas on where is the problem?

**Comment by EmanuelaBoros** [comment]
@syunusic Can you run `pip freeze | grep torch`?

**Comment by syunusic** [comment]
> @syunusic Can you run `pip freeze | grep torch`?

# pip freeze | grep torch
torch @ file:///croot/pytorch_1686931851744/work

**Comment by EmanuelaBoros** [comment]
@syunusic Can you do a `pip install torch --upgrade` and then again a `pip freeze | grep torch` ?

**Comment by syunusic** [comment]
It seems that nothing changed:
```
# pip install torch --upgrade
Requirement already satisfied: torch in /usr/local/bin/anaconda3/lib/python3.11/site-packages (2.0.1)
Requirement already satisfied: filelock in /usr/local/bin/anaconda3/lib/python3.11/site-packages (from torch) (3.9.0)
Requirement already satisfied: typing-extensions in /usr/local/bin/anaconda3/lib/python3.11/site-packages (from torch) (4.7.1)
Requirement already satisfied: sympy in /usr/local/bin/anaconda3/lib/python3.11/site-packages (from torch) (1.11.1)
Requirement already satisfied: networkx in /usr/local/bin/anaconda3/lib/python3.11/site-packages (from torch) (3.1)
Requirement already satisfied: jinja2 in /usr/local/bin/anaconda3/lib/python3.11/site-packages (from torch) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/bin/anaconda3/lib/python3.11/site-packages (from jinja2->torch) (2.1.1)
Requirement already satisfied: mpmath>=0.19 in /usr/local/bin/anaconda3/lib/python3.11/site-packages (from sympy->torch) (1.3.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
# pip freeze | grep torch
torch @ file:///croot/pytorch_1686931851744/work
```

**Comment by EmanuelaBoros** [comment]
@syunusic I see, strange. Can you also do in python:
```
import torch
print(torch.__version__)
```

**Comment by syunusic** [comment]
2.0.1

**Comment by syunusic** [comment]
Maybe is important to repeat that I installed cuda-drivers-470.199.02 because NVIDIA Tesla K80 doesn't support newer cuda drivers.

**Comment by EmanuelaBoros** [comment]
@syunusic cuda11 should be fine. My concern is with the torch path + running everything as root. Could you create a proper python env and then install the requirements from llama.


```
conda create --name python311 python=3.11 anaconda 
conda activate python311
pip install -r requirements.txt
```

**Comment by syunusic** [comment]
It worked! Kinf of.. now I have a GPU memory problem, but I guess I have to study about that now. 
This is what I did:
First, create a regular user called "sacha":
```
$ id
uid=1000(sacha) gid=1000(sacha) groups=1000(sacha) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
```
Then I create a new environment logged as this user, activate it and then install the requirements:
```
(base) [sacha@tyrion llama]$ conda create --name forllama python=3.11
...
(base) [sacha@tyrion llama]$ conda activate forllama
...
(forllama) [sacha@tyrion llama]$ pip install -e .
...
```
After that I run:
```
(forllama) [sacha@tyrion llama]$ torchrun --nproc_per_node 1 example_chat_completion.py     --ckpt_dir llama-2-7b-chat/     --tokenizer_path tokenizer.model     --max_seq_len 512 --max_batch_size 6
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "/home/sacha/llama/example_chat_completion.py", line 89, in <module>
    fire.Fire(main)
  File "/home/sacha/.conda/envs/forllama/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sacha/.conda/envs/forllama/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/sacha/.conda/envs/forllama/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sacha/llama/example_chat_completion.py", line 20, in main
    generator = Llama.build(
                ^^^^^^^^^^^^
  File "/home/sacha/llama/llama/generation.py", line 95, in build
    model = Transformer(model_args)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sacha/llama/llama/model.py", line 259, in __init__
    self.layers.append(TransformerBlock(layer_id, params))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sacha/llama/llama/model.py", line 221, in __init__
    self.attention = Attention(args)
                     ^^^^^^^^^^^^^^^
  File "/home/sacha/llama/llama/model.py", line 113, in __init__
    self.wv = ColumnParallelLinear(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sacha/.conda/envs/forllama/lib/python3.11/site-packages/fairscale/nn/model_parallel/layers.py", line 262, in __init__
    self.weight = Parameter(torch.Tensor(self.output_size_per_partition, self.in_features))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 11.17 GiB total capacity; 10.90 GiB already allocated; 28.25 MiB free; 10.90 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4022) of binary: /home/sacha/.conda/envs/forllama/bin/python
Traceback (most recent call last):
  File "/home/sacha/.conda/envs/forllama/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/sacha/.conda/envs/forllama/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/sacha/.conda/envs/forllama/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/sacha/.conda/envs/forllama/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/sacha/.conda/envs/forllama/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sacha/.conda/envs/forllama/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-31_12:55:24
  host      : tyrion.dalmacia.local
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4022)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```
Why it runs out of memory if it has 24GB of vRAM?
I know th K80 is old.. but I thought it would be more than enough to run any llama 2 flavor, even the 70B-Chat one.

**Comment by EmanuelaBoros** [comment]
@syunusic for llama-7b you need one GPU of more than 24Gb. For now it can’t be split into two GPUs. You can try a much smaller max seq length, but still the model to be loaded needs more.

**Comment by syunusic** [comment]
Oh.. I see. Where can I see the GPU specs for the different Llama Flavors? Thanks for your help.

**Comment by scurtis142** [comment]
Hi. I am getting the same error and the solution hasn't worked for me.
I have CUDA version 12.2 installed:

```
simon@:llama$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0
```
Steps I took to get the error:
```
conda create --name python311 python=3.11 anaconda
conda activate pytho
pip install -r requirements.txt
torchrun --nproc_per_node 1 example_text_completion.py     --ckpt_dir llama-2-7b/     --tokenizer_path tokenizer.model     --max_seq_len 128 --max_batch_size 4
```

Output:
```
Traceback (most recent call last):
  File "/home/simon/documents/llm/llama/example_text_completion.py", line 69, in <module>
    fire.Fire(main)
  File "/home/simon/miniconda3/envs/python311/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/miniconda3/envs/python311/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/miniconda3/envs/python311/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/documents/llm/llama/example_text_completion.py", line 32, in main
    generator = Llama.build(
                ^^^^^^^^^^^^
  File "/home/simon/documents/llm/llama/llama/generation.py", line 84, in build
    torch.distributed.init_process_group("nccl")
  File "/home/simon/miniconda3/envs/python311/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/miniconda3/envs/python311/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1013, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 39496) of binary: /home/simon/miniconda3/envs/python311/bin/python
Traceback (most recent call last):
  File "/home/simon/miniconda3/envs/python311/bin/torchrun", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/simon/miniconda3/envs/python311/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/simon/miniconda3/envs/python311/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/simon/miniconda3/envs/python311/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/simon/miniconda3/envs/python311/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/miniconda3/envs/python311/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_text_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-04_15:55:30
  host      : simon-NH50-70RH
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 39496)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

Any help would be appreciated.

**Comment by EmanuelaBoros** [comment]
@scurtis142 `nvidia-smi`?

**Comment by manoj21192** [comment]
In generation.py file, In line 61 use below code
torch.distributed.init_process_group("gloo") instead of torch.distributed.init_process_group("nccl")

**Comment by jspisak** [comment]
@syunusic - please let us know if that fixed your issue.

**Comment by syunusic** [comment]
> @syunusic - please let us know if that fixed your issue.

Nope. I gave up because what @EmanuelaBoros said (...for llama-7b you need one GPU of more than 24Gb...). I'll re try in couple of weeks.

**Comment by jspisak** [comment]
Yes, the k80 is quite an old GPU (it was frankly old when AWS first even deployed them. I'll then go ahead and close this issue. Thanks for getting back!
