### ISSUE TITLE
How to load 13B model in a single GPU?

### ISSUE THREAD

**Issue by ELFEamp** [facebookresearch/llama#78]
Hi, I want to load 13B or larger model in a single A100 80G, but find that the two shards of the model are ought to be loaded in 2 GPUs, is there any way to consolidate the two shards into one file?

**Comment by pauldog** [comment]
There might be a way to trick it using [virtual GPUs](https://www.nvidia.com/en-gb/data-center/virtual-solutions/)? Also [this](https://www.youtube.com/watch?v=Bc3LGVi5Sio).

No idea if that would work! If you get it to work let me know I'd be interesting 😁

**Comment by Logophoman** [comment]
Same issue here, using Ubuntu 20.04 and an A-100 40GB... 

The 7B model works flawlessly, however the higher MP's are turning out to be an issue... 

Funniest thing is that afaik according to Meta even the 65B should run on a +32GB Card

**Comment by fabawi** [comment]
I was able to run 7B on two 1080 Ti (only inference). Next, I'll try 13B and 33B. It still needs refining but it works! I forked LLaMA here:

https://github.com/modular-ml/wrapyfi-examples_llama

and have a readme with the instructions on how to do it:

# LLaMA with Wrapyfi

Wrapyfi enables distributing LLaMA (inference only) on multiple GPUs/machines, each with less than 16GB VRAM 

**currently distributes on two cards only using ZeroMQ. Will support flexible distribution soon!** 

**This approach has only been tested on 7B model for now, using Ubuntu 20.04 with two 1080 Tis. Testing 13B/30B models soon!**
**UPDATE: Tested on Two 3080 Tis as well!!!**

### How to?

0. Replace all instances of <YOUR_IP> and <YOUR CHECKPOINT DIRECTORY> before running the scripts
  
1. Download LLaMA weights using the official form below and install this wrapyfi-examples_llama inside conda or virtual env:

  ```
  git clone https://github.com/modular-ml/wrapyfi-examples_llama.git
  cd wrapyfi-examples_llama
  pip install -r requirements.txt
  pip install -e .
  ```

3. Install Wrapyfi with the same environment:

  ```
  git clone https://github.com/fabawi/wrapyfi.git
  cd wrapyfi
  pip install .[pyzmq]
  ```

4. Start the Wrapyfi ZeroMQ broker from within the Wrapyfi repo:

  ```
  cd wrapyfi/standalone 
  python zeromq_proxy_broker.py --comm_type pubsubpoll
  ```

5. Start the first instance of the Wrapyfi-wrapped LLaMA from within this repo and env (order is important, dont start wrapyfi_device_idx=0 before wrapyfi_device_idx=1):

  ```
  CUDA_VISIBLE_DEVICES="0" OMP_NUM_THREADS=1 torchrun --nproc_per_node 1 example.py --ckpt_dir <YOUR CHECKPOINT DIRECTORY>/checkpoints/7B --tokenizer_path <YOUR CHECKPOINT DIRECTORY>/checkpoints/tokenizer.model --wrapyfi_device_idx 1
  ```
6. Now start the second instance (within this repo and env) :

  ```
  CUDA_VISIBLE_DEVICES="1" OMP_NUM_THREADS=1 torchrun --master_port=29503 --nproc_per_node 1 example.py --ckpt_dir <YOUR CHECKPOINT DIRECTORY>/checkpoints/7B --tokenizer_path <YOUR CHECKPOINT DIRECTORY>/checkpoints/tokenizer.model --wrapyfi_device_idx 0
  ```

7. You will now see the output on both terminals

8. EXTRA: To run on different machines, the broker must be running on a specific IP in step 4. Start the ZeroMQ broker by setting the IP and provide the env variables for steps 5+6 e.g.,

  ```
  ### (replace 10.0.0.101 with <YOUR_IP> ###
  
  # step 4 modification 
  python zeromq_proxy_broker.py --socket_ip 10.0.0.101 --comm_type pubsubpoll
  
  # step 5 modification
  CUDA_VISIBLE_DEVICES="0" OMP_NUM_THREADS=1 WRAPYFI_ZEROMQ_SOCKET_IP='10.0.0.101' torchrun --nproc_per_node 1 example.py --ckpt_dir <YOUR CHECKPOINT DIRECTORY>/checkpoints/7B --tokenizer_path <YOUR CHECKPOINT DIRECTORY>/checkpoints/tokenizer.model --wrapyfi_device_idx 1
  
  # step 6 modification
  CUDA_VISIBLE_DEVICES="1" OMP_NUM_THREADS=1 WRAPYFI_ZEROMQ_SOCKET_IP='10.0.0.101' torchrun --master_port=29503 --nproc_per_node 1 example.py --ckpt_dir <YOUR CHECKPOINT DIRECTORY>/checkpoints/7B --tokenizer_path <YOUR CHECKPOINT DIRECTORY>/checkpoints/tokenizer.model --wrapyfi_device_idx 0
  ```

**Comment by cedrickchee** [comment]
> The 7B model works flawlessly, however the higher MP's are turning out to be an issue...

True. 13B MP is 2 and required 27GB VRAM. So it can run in a single A100 80GB or 40GB, but after modying the model.

Aside: if you don't know, Model Parallel (MP) encompasses both Pipeline Parallel (PP) and Tensor Parallel (TP).
PP shards layers. TP shards each tensor. People always confuse them.

> After Fiddeling around a bit I think I came up with a solution, you can indeed try to run everything on a single GPU

The model by default is configured for distributed GPU (more than 1 GPU). A modified model (`model.py`) below should works with a single GPU. In addition, I also lowered the batch size to 1 so that the model can fit within VRAM.

```py
class ModelArgs:
    dim: int = 512
    n_layers: int = 8
    n_heads: int = 8
    vocab_size: int = -1
    multiple_of: int = 256
    norm_eps: float = 1e-5

    max_batch_size: int = 1 # <-- change this line from 32

# ...

class Attention(nn.Module):
    def __init__(self, args: ModelArgs):
        super().__init__()

        self.n_local_heads = args.n_heads // 1 # <-- change this. previous: args.n_heads // fs_init.get_model_parallel_world_size()
        self.head_dim = args.dim // args.n_heads

        self.wq = nn.Linear( # <-- change line: previous: ColumnParallelLinear
            args.dim,
            args.n_heads * self.head_dim,
            bias=False,
            input_is_parallel=True, # <-- remove this line
            init_method=lambda x: x, # <-- remove this line
        )
        self.wk = nn.Linear( # <-- change line: previous: ColumnParallelLinear
            args.dim,
            args.n_heads * self.head_dim,
            bias=False,
            input_is_parallel=True, # <-- remove this line
            init_method=lambda x: x, # <-- remove this line
        )
        self.wv = nn.Linear( # <-- change line: previous: ColumnParallelLinear
            args.dim,
            args.n_heads * self.head_dim,
            bias=False,
            input_is_parallel=True, # <-- remove this line
            init_method=lambda x: x, # <-- remove this line
        )
        self.wo = nn.Linear( # <-- change line: previous: RowParallelLinear
            args.n_heads * self.head_dim,
            args.dim,
            bias=False,
            input_is_parallel=True, # <-- remove this line
            init_method=lambda x: x, # <-- remove this line
        )

# ...

class FeedForward(nn.Module):
    def __init__(
        self,
        dim: int,
        hidden_dim: int,
        multiple_of: int,
    ):
        super().__init__()
        hidden_dim = int(2 * hidden_dim / 3)
        hidden_dim = multiple_of * ((hidden_dim + multiple_of - 1) // multiple_of)

        self.w1 = nn.Linear( # <-- change this. previous: ColumnParallelLinear
            dim, hidden_dim, bias=False, gather_output=False, init_method=lambda x: x
        )
        self.w2 = nn.Linear( # <-- change this. previous: RowParallelLinear
            hidden_dim, dim, bias=False, input_is_parallel=True, init_method=lambda x: x
        )
        self.w3 = nn.Linear( # <-- change this. previous: ColumnParallelLinear
            dim, hidden_dim, bias=False, gather_output=False, init_method=lambda x: x
        )

# ...

class Transformer(nn.Module):
    def __init__(self, params: ModelArgs):
        super().__init__()
        self.params = params
        self.vocab_size = params.vocab_size
        self.n_layers = params.n_layers

        self.tok_embeddings = nn.Embedding( # <-- change this. previous: ParallelEmbedding
            params.vocab_size, params.dim
        )

        self.layers = torch.nn.ModuleList()
        for layer_id in range(params.n_layers):
            self.layers.append(TransformerBlock(layer_id, params))

        self.norm = RMSNorm(params.dim, eps=params.norm_eps)
        self.output = nn.Linear( # <-- change this. previous: ColumnParallelLinear
            params.dim, params.vocab_size, bias=False
        )

# ...
```

Modify those lines I mentioned in the code above. Basically, we removed all model parallel codes to make it work.

**Comment by neuhaus** [comment]
@cedrickchee i implemented your changes (and a few more along those lines) in my fork in the non_parallel branch at https://github.com/neuhaus/llama/tree/non_parallel

CUDA is running out of GPU memory on a RTX 3090 24GB with those changes so i'm not sure if they will work on cards with more memory.

**Comment by cedrickchee** [comment]
> i implemented your changes (and a few more along those lines) in my fork in the non_parallel branch at 

@neuhaus You are using `fire.Fire(main)` in your `example.py`. What is your max seq len & max batch size?

```py
    main(
        ckpt_dir="13B",
        tokenizer_path="tokenizer.model",
        temperature=0.8,
        top_p=0.95,
        max_seq_len=1024,
        max_batch_size=1
    )
```

If OOM, always confirm your batch size is small enough so the model can fit in your GPU VRAM. I suspect that is not the cause. It's easier if you use my `inference.py` code instead.

> CUDA is running out of GPU memory on a RTX 3090 24GB

Of course. 13B required 27GB VRAM. I run in  a single A100 40GB.

**Comment by Yuji09** [comment]
> if you use my `inference.py` code instead.



> A modified model (`model.py`) below should works with a single GPU.

@cedrickchee
I tried to use your code (model.py and inference.py) with 13B on Colab pro (I think with 64GB gpu ram). But I get the following errors.

`Traceback (most recent call last):
  File "inference.py", line 111, in <module>
    main(
  File "inference.py", line 90, in main
    generator = load(
  File "inference.py", line 66, in load
    model.load_state_dict(checkpoint, strict=False)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Transformer:
	size mismatch for tok_embeddings.weight: copying a param with shape torch.Size([32000, 2560]) from checkpoint, the shape in current model is torch.Size([32000, 5120]).
	size mismatch for layers.0.attention.wq.weight: copying a param with shape torch.Size([2560, 5120]) from checkpoint, the shape in current model is torch.Size([5120, 5120]).
	size mismatch for layers.0.attention.wk.weight: copying a param with shape torch.Size([2560, 5120]) from checkpoint, the shape in current model is torch.Size([5120, 5120]).
	size mismatch for layers.0.attention.wv.weight: copying a param with shape torch.Size([2560, 5120]) from checkpoint, the shape in current model is torch.Size([5120, 5120]).
	size mismatch for layers.0.attention.wo.weight: copying a param with shape torch.Size([5120, 2560]) from checkpoint, the shape in current model is torch.Size([5120, 5120]).
	size mismatch for layers.0.feed_forward.w1.weight: copying a param with shape torch.Size([6912, 5120]) from checkpoint, the shape in current model is torch.Size([13824, 5120]).
	size mismatch for layers.0.feed_forward.w2.weight: copying a param with shape torch.Size([5120, 6912]) from checkpoint, the shape in current model is torch.Size([5120, 13824]).
	size mismatch for layers.0.feed_forward.w3.weight: copying a param with shape torch.Size([6912, 5120]) from checkpoint, the shape in current model is torch.Size([13824, 5120]).
	size mismatch for layers.1.attention.wq.weight: copying a param with shape torch.Size([2560, 5120]) from checkpoint, the shape in current model is torch.Size([5120, 5120]).`

.. and size mismatch for many more layers.

Does the code work even with two separate pths (consolidated.00.pth, consolidated.01.pth)? Or do I need to change more?

Thanks.

**Comment by dtthanh1971** [comment]
I run with 13B on single GPU:  NVIDIA A100-SXM4-40GB (Colab Pro). What should I do?

**Comment by neuhaus** [comment]
> I run with 13B on single GPU: NVIDIA A100-SXM4-40GB (Colab Pro). What should I do?

Be happy? It seems to be working for you.

**Comment by vencolini** [comment]
Can we adjust this to fit 

> > i implemented your changes (and a few more along those lines) in my fork in the non_parallel branch at
> 
> @neuhaus You are using `fire.Fire(main)` in your `example.py`. What is your max seq len & max batch size?
> 
> ```python
>     main(
>         ckpt_dir="13B",
>         tokenizer_path="tokenizer.model",
>         temperature=0.8,
>         top_p=0.95,
>         max_seq_len=1024,
>         max_batch_size=1
>     )
> ```
> 
> If OOM, always confirm your batch size is small enough so the model can fit in your GPU VRAM. I suspect that is not the cause. It's easier if you use my `inference.py` code instead.
> 
> > CUDA is running out of GPU memory on a RTX 3090 24GB
> 
> Of course. 13B required 27GB VRAM. I run in a single A100 40GB.

Anyone with an inspiration how to adjust and fit the 13B model on a single 24GB RTX 3090 or RTX 4090. Now the 13B model  takes only 3GB more than what available on these GPUs. 

Or anybody knows how much the accuracy of the 13B model will be affected by using int8 - https://github.com/tloen/llama-int8 ?

**Comment by jspisak** [comment]
transferring to the llama-recipes repo as it's a better fit for this issue..
