### ISSUE TITLE
AssertionError: no checkpoint files found in llama-2-7b-chat/

### ISSUE THREAD

**Issue by FaizanMunsaf** [facebookresearch/llama#789]
torchrun --nproc_per_node 2 example_chat_completion.py     --ckpt_dir llama-2-7b-chat/     --tokenizer_path tokenizer.model     --max_seq_len 512 --max_batch_size 6
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
> initializing model parallel with size 2
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "/root/test/example_chat_completion.py", line 104, in <module>
    fire.Fire(main)
  File "/root/anaconda3/envs/islamicgpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/anaconda3/envs/islamicgpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/anaconda3/envs/islamicgpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/test/example_chat_completion.py", line 35, in main
    generator = Llama.build(
  File "/root/test/llama/generation.py", line 101, in build
    assert len(checkpoints) > 0, f"no checkpoint files found in {ckpt_dir}"
AssertionError: no checkpoint files found in llama-2-7b-chat/
Traceback (most recent call last):
  File "/root/test/example_chat_completion.py", line 104, in <module>
    fire.Fire(main)
  File "/root/anaconda3/envs/islamicgpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/anaconda3/envs/islamicgpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/anaconda3/envs/islamicgpt/lib/pythonec2-3-64-163-50.eu-central-1.compute.amazonaws.com3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/test/example_chat_completion.py", line 35, in main
    generator = Llama.build(
  File "/root/test/llama/generation.py", line 101, in build
    assert len(checkpoints) > 0, f"no checkpoint files found in {ckpt_dir}"
AssertionError: no checkpoint files found in llama-2-7b-chat/
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 6364) of binary: /root/anaconda3/envs/islamicgpt/bin/python
Traceback (most recent call last):
  File "/root/anaconda3/envs/islamicgpt/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/islamicgpt/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/anaconda3/envs/islamicgpt/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/root/anaconda3/envs/islamicgpt/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/anaconda3/envs/islamicgpt/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/anaconda3/envs/islamicgpt/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-09-14_05:59:45
  host      : 
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 6365)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-14_05:59:45
  host      : 
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 6364)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by fbnav** [comment]
Are you running the command from the main directory where you cloned the repo into? Your checkpoint directory might be pointing to a different location.

The –nproc_per_node should also be set to the model-parallel (MP) value for the model you are using (https://github.com/facebookresearch/llama#inference). Since you’re using llama-2-7b-chat, maybe also try setting the nproc_per_node to 1?

**Comment by FaizanMunsaf** [comment]
> Are you running the command from the main directory where you cloned the repo into? Your checkpoint directory might be pointing to a different location.
> 
> The –nproc_per_node should also be set to the model-parallel (MP) value for the model you are using (https://github.com/facebookresearch/llama#inference). Since you’re using llama-2-7b-chat, maybe also try setting the nproc_per_node to 1?


Thanks for your Answer I resolve this issue and Yes my folder was missplace I correct it and now this issue is resolve and there's no nproc issue. Now I am at that stage where I am facing GPU issue. I am correcting it

**Comment by keiaus** [comment]
How do we know where our checkpoint directory is located and what would be the name of it? Also, would I put:

```
torchrun --nproc_per_node 1 1 example_chat_completion.py \
    --ckpt_dir llama-2-7b-chat/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 512 --max_batch_size 6
```

for referencing a 7B model?
