### ISSUE TITLE
Signal 11 (SIGSEGV) received

### ISSUE THREAD

**Issue by Milan933** [facebookresearch/llama#799]
Has anyone seen a similar error?
I want to run llama on Kubuntu 22.04, with an RX 6700XT, I also installed the AMD driver, ROCm, but I can't deal with this part anymore.Maybe someone has an idea how to request more logos from there?

````
root@porada:/home/porada/llama/llama# torchrun --nproc_per_node 1 example_chat_completion.py     --ckpt_dir llama-2-7b-chat/     --tokenizer_path tokenizer.model     --max_seq_len 512 --max_batch_size 6
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -11) local_rank: 0 (pid: 82397) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=======================================================
example_chat_completion.py FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-16_16:52:33
  host      : porada
  rank      : 0 (local_rank: 0)
  exitcode  : -11 (pid: 82397)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 82397
=======================================================
```
`

**Comment by jspisak** [comment]
This issue should be opened up in pytorch/pytorch and tagged as AMD.
