### ISSUE TITLE
AssertionError: Loading a checkpoint for MP=8 but world size is 1

### ISSUE THREAD

**Issue by 1ceberg9** [facebookresearch/llama#806]
Hi guys, I got an error while trying to deploy llama-2-70b-chat。

torchrun --nproc_per_node 1 example_text_completion.py \
     --ckpt_dir /home/user/imported_models/llama-2-70b-chat/Llama-2-70b-chat \
     --tokenizer_path /home/user/imported_models/llama-2-70b-chat/Llama-2-70b-chat/tokenizer.model \
     --max_seq_len 128 --max_batch_size 4
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "/home/user/data/llama/example_text_completion.py", line 69, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/user/data/llama/example_text_completion.py", line 32, in main
    generator = Llama.build(
  File "/home/user/data/llama/llama/generation.py", line 103, in build
    assert model_parallel_size == len(
AssertionError: Loading a checkpoint for MP=8 but world size is 1
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3819) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_text_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-19_02:56:56
  host      : lsp-ws
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3819)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

Which kind person can help me？QAQ

**Comment by EmanuelaBoros** [comment]
Hello @1ceberg9 , how many GPUs do you have? This model needs 8.

**Comment by 1ceberg9** [comment]
> Hello @1ceberg9 , how many GPUs do you have? This model needs 8.
Thank you! I found the problem

**Comment by bhargavanubavam** [comment]
Hi guys, I got an error while trying to deploy llama-2-70b-chat

Command:
torchrun --nproc_per_node 8 example_chat_completion.py \
    --ckpt_dir llama-2-70b-chat/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 512 --max_batch_size 6

Error:

> initializing model parallel with size 8
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "/olddata/llama/example_chat_completion.py", line 104, in <module>
    fire.Fire(main)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/olddata/llama/example_chat_completion.py", line 35, in main
    generator = Llama.build(
  File "/olddata/llama/llama/generation.py", line 103, in build
    assert model_parallel_size == len(
AssertionError: Loading a checkpoint for MP=2 but world size is 8


I have cloned the llama2 github repo, downloaded the model using download.sh and using example_chat_completion.py file, I am running on AWS EC2 instance with 8 GPUs.

**Comment by Jorya2333** [comment]
"Hello everyone, I would like to ask for your advice. If I don't have 8 GPUs, do you have any suggestions or alternative solutions? Thank you!"

**Comment by AGenchev** [comment]
@Jorya2333 I have the same problem. Until I find a real solution with pytorch for 4 GPU, just to test the model, I'll try to convert it in Georgi Gerganov's GGUF format and will try his llama.cpp.
