### ISSUE TITLE
AssertionError: no checkpoint files found in  --ckpt_dir

### ISSUE THREAD

**Issue by widzKid** [facebookresearch/llama#825]
I am attempting to run Llama 2 per the basic instructions:

`torchrun --nproc_per_node 1 example_chat_completion.py \ --ckpt_dir llama-2-7b-chat/ \ --tokenizer_path tokenizer.model \ --max_seq_len 512 --max_batch_size 6`
 
and receive the following:

```
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "/home/pedro/llama/example_chat_completion.py", line 104, in <module>
    fire.Fire(main)
  File "/home/pedro/anaconda3/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/anaconda3/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/anaconda3/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/llama/example_chat_completion.py", line 35, in main
    generator = Llama.build(
                ^^^^^^^^^^^^
  File "/home/pedro/llama/llama/generation.py", line 102, in build
    assert len(checkpoints) > 0, f"no checkpoint files found in {ckpt_dir}"
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: no checkpoint files found in  --ckpt_dir
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 80232) of binary: /home/pedro/anaconda3/bin/python
Traceback (most recent call last):
  File "/home/pedro/anaconda3/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.0.post200', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/anaconda3/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/pedro/anaconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/pedro/anaconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/pedro/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-23_05:45:48
  host      : pedro-ROG-Zephyrus-G15-GA503RM-GA503RM
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 80232)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```
Looking at the following error, I have made sure that I am in the directory in which the llama models were downloaded into:
#577 

In the llama-2-7b-chat folder I have: checklist.chk, consolidated.00.pth, and params.json

Any help would be appreciated.

**Comment by fbnav** [comment]
Maybe try running the command without any spaces following the '\', as this could be escaping the character and not finding the checkpoint files. Could you try either of the following:

Run the command in one line :
`torchrun --nproc_per_node 1 example_chat_completion.py --ckpt_dir llama-2-7b-chat/  --tokenizer_path tokenizer.model --max_seq_len 512 --max_batch_size 6`

Or without any trailing spaces :
`torchrun --nproc_per_node 1 example_chat_completion.py \--ckpt_dir llama-2-7b-chat/ \--tokenizer_path tokenizer.model \--max_seq_len 512 --max_batch_size 6`

**Comment by fbnav** [comment]
Closing this issue for now, please reopen if you need to follow-up.
