### ISSUE TITLE
Fire module not found when running example script. Please help.

### ISSUE THREAD

**Issue by Harsh-raj** [facebookresearch/llama#843]
Traceback (most recent call last):
  File "example_chat_completion.py", line 4, in <module>
    import fire
ModuleNotFoundError: No module named 'fire'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2798750) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/home/surbhi/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/surbhi/.local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/surbhi/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/surbhi/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/surbhi/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/surbhi/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-08_18:33:49
  host      : surbhi
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2798750)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

I have installed fire using pip but it always throw ModuleNotFoundError. I am using remote ssh to container with python environment and python 3.11.x and fire 0.5.0 install. What am i missing?

**Comment by Harsh-raj** [comment]
update: i reduced python version to 3.8.11 now. still it is not working.

**Comment by Harsh-raj** [comment]
I solved this problem by using `python -m torch.distributed.run` instead of `torchrun` as it seems to have some bugs that prevents fire work along with it.

**Comment by IgorGanapolskyGit** [comment]
I get this error:
> RuntimeError: Distributed package doesn't have NCCL built in
