### ISSUE TITLE
RuntimeError: The expanded size of the tensor (22528) must match the existing size (1024) at non-singleton dimension 0

### ISSUE THREAD

**Issue by jehalvar** [facebookresearch/llama#854]
Hi all,

We are running a setup where we utilize runpod, where we can download and utilize the 7b and 13b model, while below error is present when we try to utilize the 70b model. 

Any idea what can cause this?

2023-10-10T10:55:50.329412059Z   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 131, in load_weights
2023-10-10T10:55:50.329412900Z     module._parameters[param_name][value.shape[0] * 2 :] = value
2023-10-10T10:55:50.329413751Z RuntimeError: The expanded size of the tensor (22528) must match the existing size (1024) at non-singleton dimension 0.  Target sizes: [22528, 8192].  Tensor sizes: [1024, 8192]
2023-10-10T10:55:50.329415123Z  rank=0
2023-10-10T10:55:51.275395485Z Error: ShardCannotStart
2023-10-10T10:55:51.275419161Z 2023-10-10T10:55:51.275248Z ERROR text_generation_launcher: Shard 0 failed to start:
2023-10-10T10:55:51.275440002Z Traceback (most recent call last):
2023-10-10T10:55:51.275441445Z 
2023-10-10T10:55:51.275442767Z   File "/opt/conda/bin/text-generation-server", line 8, in <module>
2023-10-10T10:55:51.275444099Z     sys.exit(app())
2023-10-10T10:55:51.275444990Z 
2023-10-10T10:55:51.275445931Z   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 67, in serve
2023-10-10T10:55:51.275447323Z     server.serve(model_id, revision, sharded, quantize, trust_remote_code, uds_path)
2023-10-10T10:55:51.275448205Z 
2023-10-10T10:55:51.275449026Z   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 155, in serve
2023-10-10T10:55:51.275450418Z     asyncio.run(serve_inner(model_id, revision, sharded, quantize, trust_remote_code))
2023-10-10T10:55:51.275451249Z 
2023-10-10T10:55:51.275452041Z   File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
2023-10-10T10:55:51.275452792Z     return loop.run_until_complete(main)
2023-10-10T10:55:51.275453703Z 
2023-10-10T10:55:51.275454504Z   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
2023-10-10T10:55:51.275455426Z     return future.result()
2023-10-10T10:55:51.275456688Z 
2023-10-10T10:55:51.275457349Z   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 124, in serve_inner
2023-10-10T10:55:51.275458360Z     model = get_model(model_id, revision, sharded, quantize, trust_remote_code)
2023-10-10T10:55:51.275459191Z 
2023-10-10T10:55:51.275459953Z   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 246, in get_model
2023-10-10T10:55:51.275474935Z     return llama_cls(
2023-10-10T10:55:51.275475937Z 
2023-10-10T10:55:51.275476778Z   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 67, in __init__
2023-10-10T10:55:51.275477729Z     self.load_weights(model, filenames, quantize, device, dtype)
2023-10-10T10:55:51.275479121Z 
2023-10-10T10:55:51.275479953Z   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 131, in load_weights
2023-10-10T10:55:51.275480874Z     module._parameters[param_name][value.shape[0] * 2 :] = value
2023-10-10T10:55:51.275481685Z 
2023-10-10T10:55:51.275482547Z RuntimeError: The expanded size of the tensor (22528) must match the existing size (1024) at non-singleton dimension 0.  Target sizes: [22528, 8192].  Tensor sizes: [1024, 8192]
2023-10-10T10:55:51.275484029Z

**Comment by wudijimao** [comment]
I have the same problem

**Comment by jehalvar** [comment]
> I have the same problem

The issue, for me, was that we used a to old version of text-generation-inference (0.8.2) which doesnt support llama 2 70b model. Bumped it up to 0.9.3 and it worked.
