### ISSUE TITLE
hi,could you help me for llama2-13b-chat-hf

### ISSUE THREAD

**Issue by ucas010** [facebookresearch/llama#871]
```python
torchrun --nproc_per_node 1 ../llama/example_text_completion.py --ckpt_dir ../conf/llama2-13b-chat-hf/ --tokenizer_path ../conf/llama2-13b-chat-hf/tokenizer.model --max_seq_len 512 --max_batch_size 1
```

### Output

```
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "/d/llama/../llama/example_text_completion.py", line 55, in <module>
    fire.Fire(main)
  File "/dg/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/dg/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/dg/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/d/llama/../llama/example_text_completion.py", line 18, in main
    generator = Llama.build(
  File "/d/llama/llama/generation.py", line 78, in build
    assert len(checkpoints) > 0, f"no checkpoint files found in {ckpt_dir}"
AssertionError: no checkpoint files found in ../conf/llama2-13b-chat-hf/
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 30514) of binary: /dg/bin/python
Traceback (most recent call last):
  File "/dg/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/dg/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/dg/lib/python3.9/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/dg/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/dg/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/dg/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
../llama/example_text_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-23_10:59:38
  host      : localhost.localdomain
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 30514)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

## Runtime Environment
- Model: [eg: `llama-2-7b-chat`] llama2-13b-chat-hf
- Using via huggingface?: [yes/no] yes
- OS: [eg. Linux/Ubuntu, Windows] Linux
- GPU VRAM: 
- Number of GPUs: 1
- GPU Make: [eg: Nvidia, AMD, Intel] Nvidia

**Additional context**
Add any other context about the problem or environment here.

**Comment by Uxiang** [comment]
Please use the absolute path for model path

**Comment by subramen** [comment]
Since you are using the huggingface checkpoints, try running the huggingface example: https://huggingface.co/blog/llama2#using-transformers

The scripts/examples in this repo assumes use of the checkpoints from Meta
