### ISSUE TITLE
Error in ChildFailedError

### ISSUE THREAD

**Issue by Vatsal1106Virani** [facebookresearch/llama#881]
## Describe the bug
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
I have issue while running " torchrun --nproc_per_node 1 example_chat_completion.py \
    --ckpt_dir llama-2-7b-chat/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 512 --max_batch_size 6 "

"""
ModuleNotFoundError: No module named 'fairscale'
[2023-10-27 20:02:28,320] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 46862) of binary: /home/ob-90/anaconda3/bin/python
Traceback (most recent call last):
  File "/home/ob-90/anaconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ob-90/anaconda3/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ob-90/anaconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/ob-90/anaconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/ob-90/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ob-90/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-27_20:02:28
  host      : ob-90
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 46862)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

"""

## Runtime Environment
- Model: llama-2-7b
- Using via huggingface?: no
- OS: Linux Ubantu 22.04
- GPU VRAM: Mesa Intel® UHD Graphics 730 (ADL-S GT1)
- Number of GPUs: 1
- GPU Make: Intel

**Comment by subramen** [comment]
It looks like your setup is missing fairscale. Also currently we only support NVIDIA GPUs, so maybe that might also be causing an issue.

Closing this now, please reopen if you need to follow-up.

**Comment by Vatsal1106Virani** [comment]
> It looks like your setup is missing fairscale. Also currently we only support NVIDIA GPUs, so maybe that might also be causing an issue.
> 
> Closing this now, please reopen if you need to follow-up.

Which version of NVIDIA GPUs is required with cuda version?
