### ISSUE TITLE
Incorrect attention mask breaks key-value caching

### ISSUE THREAD

**Issue by flu0r1ne** [facebookresearch/llama#899]
## Describe the bug

There is currently a bug in the model relating to key-value caching. A square attention mask is misapplied to the scores matrix despite not matching the shape of the scores matrix. This results in a runtime error.

### Minimal reproducible example

```python
import torch
import fire

from llama import Llama

def main(
    checkpoint_directory: str,
    tokenizer_path: str,
):
    generator = Llama.build(
        checkpoint_directory,
        tokenizer_path,
        max_seq_len=200,
        max_batch_size=1
    )

    model = generator.model
    tokenizer = generator.tokenizer

    tokens = torch.tensor([
        tokenizer.encode("Aperture Science. We do what we must, because we can.", bos=True, eos=False)
    ], dtype=torch.long)

    PART = 7
    _, seqlen = tokens.shape

    for start, end in ((0, PART), (PART, seqlen), (0, seqlen)):
        seq = tokens[:, start:end]

        s = tokenizer.decode(seq.tolist())
        print(f'[{start}, {end}) {s}')

        vocab_logprobs = model(seq, start)
        print('log probs: ', vocab_logprobs[:,-1])

if __name__ == '__main__':
    fire.Fire(main)
```

### Output

```
Loaded in 45.41 seconds
[0, 7) ['Aperture Science. We']
log probs:  tensor([[ -9.5338, -10.2840,   2.4404,  ...,  -6.1215,  -7.6857,  -5.3498]])
[7, 16) ['do what we must, because we can.']
Traceback (most recent call last):
  File "/home/flu0r1ne/dev/llama/example_kv_caching.py", line 37, in <module>
    fire.Fire(main)
  File "/home/flu0r1ne/micromamba/envs/torch/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/flu0r1ne/micromamba/envs/torch/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/flu0r1ne/micromamba/envs/torch/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/flu0r1ne/dev/llama/example_kv_caching.py", line 33, in main
    vocab_logprobs = model(seq, start)
  File "/home/flu0r1ne/micromamba/envs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/flu0r1ne/micromamba/envs/torch/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/flu0r1ne/dev/llama/llama/model.py", line 496, in forward
    h = layer(h, start_pos, freqs_cis, mask)
  File "/home/flu0r1ne/micromamba/envs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/flu0r1ne/dev/llama/llama/model.py", line 406, in forward
    h = x + self.attention.forward(
  File "/home/flu0r1ne/dev/llama/llama/model.py", line 300, in forward
    scores = scores + mask  # (bs, n_local_heads, seqlen, cache_len + seqlen)
  File "/home/flu0r1ne/micromamba/envs/torch/lib/python3.10/site-packages/torch/utils/_device.py", line 62, in __torch_function__
    return func(*args, **kwargs)
RuntimeError: The size of tensor a (16) must match the size of tensor b (9) at non-singleton dimension 3
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 722434) of binary: /home/flu0r1ne
```

### Expected Output

```
[0, 7) ['Aperture Science. We']
log probs:  tensor([[ -9.5338, -10.2840,   2.4404,  ...,  -6.1215,  -7.6857,  -5.3498]])
[7, 16) ['do what we must, because we can.']
log probs:  tensor([[ -8.4581, -10.0040,  11.3636,  ...,  -3.1335,  -5.0231,  -4.0460]])
[0, 16) ['Aperture Science. We do what we must, because we can.']
log probs:  tensor([[ -8.4581, -10.0040,  11.3636,  ...,  -3.1335,  -5.0231,  -4.0460]])
```

## Runtime Environment
- Model: Any
- Using via huggingface?: No
- OS: Linux 6.1.55-1-lts
- GPU VRAM:  N/A
- Number of GPUs: N/A
- GPU Make: N/A

**Comment by flu0r1ne** [comment]
Didn't see this until now but this is a duplicate of #494.

**Comment by javier-m** [comment]
Indeed, but the `Transformer.forward` method is not meant to be called directly, but wrapped within `Llama.generate`.

When calling `Transformer.forward(self, tokens, pos)`:
1) either `pos` is `0` (to compute the initial KV), or
2) `tokens` is of size `(batch_size, 1)`

In the example provided, `model(seq, start)` where `seq=tokens[:, 7:16]` and `start=7`, it is not supposed to work. The right way to do it should have been `model(seq, 0)`

**Comment by flu0r1ne** [comment]
Thank you for taking the time to look at this issue.

If I understand the codebase correctly, I agree that this doesn't affect the `Llama.generate` API. If you only utilize caching when generating single tokens, things work. If you only intend the forward method to generate single tokens, I would consider documenting this constraint. From the way the attention mask is currently calculated, it doesn't seem clear this was the intention. Additionally, in many contexts, this may offer significant efficiency gains. For instance, in a chat context when the user enters messages greater than a single token, you can rely on the previous cache instead of invalidating it.

**Comment by ruanslv** [comment]
Fix in https://github.com/facebookresearch/llama/pull/900
