### ISSUE TITLE
torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 403477) of binary: /usr/bin/python3

### ISSUE THREAD

**Issue by Jcoder410** [facebookresearch/llama#928]
## Describe the bug
I have download the llama-2-13b-chat, but when I run the commond as fallow, I got errors:
>LOGLEVEL=DEBUG torchrun --nproc_per_node gpu example_chat_completion.py \
>    --ckpt_dir llama-2-13b-chat/ \
>    --tokenizer_path tokenizer.model \
>    --max_seq_len 512 --max_batch_size 8

to get error stack, I modified the example_chat_completion.py, but I got nothing, not any error stack has been written into log file.
>from torch.distributed.elastic.multiprocessing.errors import record
@record
>def main(...):
### Output
```
INFO:torch.distributed.run:Using nproc_per_node=gpu, seting to 2 since the instance has 8 gpu
INFO:torch.distributed.launcher.api:Starting elastic_operator with launch configs:
  entrypoint       : example_chat_completion.py
  min_nodes        : 1
  max_nodes        : 1
  nproc_per_node   : 2
  run_id           : none
  rdzv_backend     : static
  rdzv_endpoint    : 127.0.0.1:29500
  rdzv_configs     : {'rank': 0, 'timeout': 900}
  max_restarts     : 0
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

INFO:torch.distributed.elastic.agent.server.local_elastic_agent:log directory set to: /tmp/torchelastic_3761yh4c/none_em3hdefe
INFO:torch.distributed.elastic.agent.server.api:[default] starting workers for entrypoint: python3
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0, 1]
  role_ranks=[0, 1]
  global_ranks=[0, 1]
  role_world_sizes=[2, 2]
  global_world_sizes=[2, 2]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.agent.server.local_elastic_agent:Environment variable 'TORCHELASTIC_ENABLE_FILE_TIMER' not found. Do not start FileTimerServer.
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_3761yh4c/none_em3hdefe/attempt_0/0/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker1 reply file to: /tmp/torchelastic_3761yh4c/none_em3hdefe/attempt_0/1/error.json
> initializing model parallel with size 2
> initializing ddp with size 1
> initializing pipeline with size 1
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 403605 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 1 (pid: 403606) of binary: /usr/bin/python3
INFO:torch.distributed.elastic.agent.server.api:Local worker group finished (FAILED). Waiting 300 seconds for other agents to finish
INFO:torch.distributed.elastic.agent.server.api:Done waiting for other agents. Elapsed: 0.0144805908203125 seconds
INFO:torch.distributed.elastic.multiprocessing.errors:local_rank 1 FAILED with no error file. Decorate your entrypoint fn with @record for traceback info. See: https://pytorch.org/docs/stable/elastic/errors.html
Traceback (most recent call last):
  File "/home/hzero/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/hzero/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/hzero/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/hzero/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/hzero/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/hzero/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=======================================================
example_chat_completion.py FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-15_23:19:13
  host      : hzero-MS-7C22
  rank      : 1 (local_rank: 1)
  exitcode  : -9 (pid: 403606)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 403606
=======================================================
```

## Runtime Environment
- Model: llama-2-13b-chat
- Using via huggingface?: no
- OS: Ubuntu 22.04
- GPU VRAM: 48G
- Number of GPUs: 2
- GPU Make: NVIDIA Corporation GA102 [GeForce RTX 3090]

**Additional context**

**Comment by letMarchezi** [comment]
I'm having the same error. The 7B-chat model works fine, but I dont know what's wrong with 13B.
PS: I only cloned the repository and downloaded the model, is it necessary to change anything else before running the 13B?

Running on:
Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
OS: CentOS Linux release 7.9.2009 (Core) (x86_64)
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-80GB

**Comment by RabiaSamad** [comment]
torch.distributed.init_process_group("gloo") 
 
  just write this line of code in example chat_completion.py and it will work

**Comment by Jcoder410** [comment]
> torch.distributed.init_process_group("gloo")
> 
> just write this line of code in example chat_completion.py and it will work

Thank your, I tried and it didn't work

**Comment by RabiaSamad** [comment]
Check system resource utilization (CPU, memory, GPU) during the execution of your program. It's possible that the process is being terminated due to resource exhaustion.

**Comment by Jcoder410** [comment]
> Check system resource utilization (CPU, memory, GPU) during the execution of your program. It's possible that the process is being terminated due to resource exhaustion.

It only consumes CPU, not GPU. I suspect the execution did not call the GPU. I am confused.

**Comment by Jcoder410** [comment]
can run 7B, and the memory is not enough for 13B

**Comment by Gabriellamin** [comment]
Hi, how did you solve the problem? I encountered the same problem.

**Comment by JJSeah** [comment]
Hi, Similar issue here any fixes for this ?

**Comment by piregler** [comment]
Same issue
Modell: llama-2-7b
macOS m1 14.2.1 (23C71)
conda 23.11.0
Python 3.8.18
torch             2.1.2.post2

This is my error:
torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "example_chat_completion.py", line 104, in <module>
    fire.Fire(main)
  File "/Users/stefanmuller/miniforge3/envs/pytorch_env/lib/python3.8/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/stefanmuller/miniforge3/envs/pytorch_env/lib/python3.8/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/stefanmuller/miniforge3/envs/pytorch_env/lib/python3.8/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "example_chat_completion.py", line 35, in main
    generator = Llama.build(
  File "/Users/stefanmuller/code/praxisemester/llama/llama/generation.py", line 85, in build
    torch.distributed.init_process_group("nccl")
  File "/Users/stefanmuller/miniforge3/envs/pytorch_env/lib/python3.8/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
  File "/Users/stefanmuller/miniforge3/envs/pytorch_env/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1148, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "/Users/stefanmuller/miniforge3/envs/pytorch_env/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1268, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL built in")
RuntimeError: Distributed package doesn't have NCCL built in
[2024-03-11 22:49:18,455] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 46395) of binary: /Users/stefanmuller/miniforge3/envs/pytorch_env/bin/python
Traceback (most recent call last):
  File "/Users/stefanmuller/miniforge3/envs/pytorch_env/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/Users/stefanmuller/miniforge3/envs/pytorch_env/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/Users/stefanmuller/miniforge3/envs/pytorch_env/lib/python3.8/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/Users/stefanmuller/miniforge3/envs/pytorch_env/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/Users/stefanmuller/miniforge3/envs/pytorch_env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/Users/stefanmuller/miniforge3/envs/pytorch_env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-11_22:49:18
  host      : 254.0.168.192.in-addr.arpa
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 46395)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by ishcha** [comment]
Same issue! Did anyone manage to resolve this?
@Jcoder410 ?

**Comment by amew0** [comment]
Please update if you solved this issue.

**Comment by luckyyf0517** [comment]
> Same issue! Did anyone manage to resolve this? [@Jcoder410](https://github.com/Jcoder410) ?

I found that use too many 'open(xxx)' instead of 'with open(xxx)' in the dataset __getitem__ will cause the system to kill the process, without any error traceback. Hope this will be useful.
