### ISSUE TITLE
## Describe the bug

### ISSUE THREAD

**Issue by Eyryu** [facebookresearch/llama#930]
## Describe the bug
I have download the llama-2-13b-chat, but when I run the commond as fallow, I got errors:
>LOGLEVEL=DEBUG torchrun --nproc_per_node gpu example_chat_completion.py \
>    --ckpt_dir llama-2-13b-chat/ \
>    --tokenizer_path tokenizer.model \
>    --max_seq_len 512 --max_batch_size 8

to get error stack, I modified the example_chat_completion.py, but I got nothing, not any error stack has been written into log file.
>from torch.distributed.elastic.multiprocessing.errors import record
@record
>def main(...):
### Output
```
INFO:torch.distributed.run:Using nproc_per_node=gpu, seting to 2 since the instance has 8 gpu
INFO:torch.distributed.launcher.api:Starting elastic_operator with launch configs:
  entrypoint       : example_chat_completion.py
  min_nodes        : 1
  max_nodes        : 1
  nproc_per_node   : 2
  run_id           : none
  rdzv_backend     : static
  rdzv_endpoint    : 127.0.0.1:29500
  rdzv_configs     : {'rank': 0, 'timeout': 900}
  max_restarts     : 0
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

INFO:torch.distributed.elastic.agent.server.local_elastic_agent:log directory set to: /tmp/torchelastic_3761yh4c/none_em3hdefe
INFO:torch.distributed.elastic.agent.server.api:[default] starting workers for entrypoint: python3
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0, 1]
  role_ranks=[0, 1]
  global_ranks=[0, 1]
  role_world_sizes=[2, 2]
  global_world_sizes=[2, 2]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.agent.server.local_elastic_agent:Environment variable 'TORCHELASTIC_ENABLE_FILE_TIMER' not found. Do not start FileTimerServer.
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_3761yh4c/none_em3hdefe/attempt_0/0/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker1 reply file to: /tmp/torchelastic_3761yh4c/none_em3hdefe/attempt_0/1/error.json
> initializing model parallel with size 2
> initializing ddp with size 1
> initializing pipeline with size 1
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 403605 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 1 (pid: 403606) of binary: /usr/bin/python3
INFO:torch.distributed.elastic.agent.server.api:Local worker group finished (FAILED). Waiting 300 seconds for other agents to finish
INFO:torch.distributed.elastic.agent.server.api:Done waiting for other agents. Elapsed: 0.0144805908203125 seconds
INFO:torch.distributed.elastic.multiprocessing.errors:local_rank 1 FAILED with no error file. Decorate your entrypoint fn with @record for traceback info. See: https://pytorch.org/docs/stable/elastic/errors.html
Traceback (most recent call last):
  File "/home/hzero/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/hzero/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/hzero/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/hzero/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/hzero/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/hzero/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=======================================================
example_chat_completion.py FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-15_23:19:13
  host      : hzero-MS-7C22
  rank      : 1 (local_rank: 1)
  exitcode  : -9 (pid: 403606)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 403606
=======================================================
```

## Runtime Environment
- Model: llama-2-13b-chat
- Using via huggingface?: no
- OS: Ubuntu 22.04
- GPU VRAM: 48G
- Number of GPUs: 2
- GPU Make: NVIDIA Corporation GA102 [GeForce RTX 3090]

**Additional context**

_オリジナルは @Jcoder410 が https://github.com/facebookresearch/llama/issues/928 にポスト_

**Comment by dhullyeny** [comment]
minha conta foi suspensa injustamente, peço que volte ao acesso pois não estou violando nenhuma diretrizes do Instagram.
nome de usuário: dhullywr 
e-mail: dhullyenyb@gmail.com
![Screenshot_20241201-180825](https://github.com/user-attachments/assets/bf0fe504-d173-4315-a6cb-e5fa525eb7c4)
